output "id" {
  description = "The Application ID generated by AWS"
  value       = aws_appconfig_application.pge_app.id
}

output "arn" {
  description = "The Application ARN generated by AWS"
  value       = aws_appconfig_application.pge_app.arn
}

output "tags" {
  description = "All tags associated with the application."
  value       = aws_appconfig_application.pge_app.tags_all
}

