# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  exported-variables:
    - ARTIFACT_VERSION
    - PROJECT_NAME
    - PROJECT_ROOT_DIRECTORY
    - PROJECT_UNIT_TEST_DIRECTORY
    - ARTIFACTORY_REPO_KEY
    - RUNTIME_VERSION
    - ARTIFACTORY_HOST

  variables:
    SONAR_TOKEN            : "${SONAR_TOKEN}"
    SONAR_HOST             : "${SONAR_HOST}"
    ARTIFACTORY_TOKEN      : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH        : "${GIT_REPO_BRANCH}"
    PROJECT_NAME           : "${PROJECT_NAME}"
    ARTIFACTORY_REPO_KEY   : "${ARTIFACTORY_REPO_KEY}"
    RUNTIME_VERSION        : "${RUNTIME_VERSION}"
    ARTIFACTORY_HOST       : "${ARTIFACTORY_HOST}"
    UNIT_TEST_COMMANDS     : "${UNIT_TEST_COMMANDS}"
    BUILD_COMMAND          : "${BUILD_COMMAND}"

phases:
  install:
    runtime-versions:
      nodejs: $RUNTIME_VERSION_CODESCAN
    commands:

      - echo "Install jq"
      - yum install -y jq

      - echo "Entered the installation phase..."
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version

      - npm config set registry "${ARTIFACTORY_HOST}"/artifactory/api/npm/"${ARTIFACTORY_REPO_KEY}"/
      - curl -u "${ARTIFACTORY_USER}":"${ARTIFACTORY_TOKEN}" "${ARTIFACTORY_HOST}"/artifactory/api/npm/auth >> .npmrc
      - npm config fix
      - echo listing files and directories
      - ls -lart
      
      # Jfrog server conifguration
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - jf rt ping
      - jf c s
      
      - echo "Install SonarScanner"
      - jf npm install -g sonarqube-scanner

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo `curl --version`
      - echo "SONAR_HOST - $SONAR_HOST"
      - echo "PROJECT_NAME - $PROJECT_NAME"
      - echo "ARTIFACT_VERSION - $ARTIFACT_VERSION"
      - echo present working directory `pwd`
      - sonar-scanner --version
  build:
    commands:
      - echo Build started on `date`
      - echo present working directory `pwd`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - eval $BUILD_COMMAND
      - echo "running unit tests with following command $UNIT_TEST_COMMANDS"
      - eval $UNIT_TEST_COMMANDS
      # Running Sonar Code Analysis
      - echo "Running Sonar Analysis"
      - sonar-scanner  -Dsonar.projectKey="${PROJECT_KEY}" -Dsonar.projectName="${PROJECT_NAME}"  -Dsonar.host.url="${SONAR_HOST}"  -Dsonar.token="${SONAR_TOKEN}" -Dsonar.branch.name=$GIT_REPO_BRANCH
      # checking quality gate status
      - cat .scannerwork/report-task.txt
      - export cetaskid=$(cat .scannerwork/report-task.txt | grep ceTaskId | cut -d'=' -f2)
      # To get the status of the analysis in the sonar server
      - curl -u "$SONAR_TOKEN:" $SONAR_HOST/api/ce/task?id=$cetaskid > status.json
      - cat status.json
      - export START=$(date +%s)
      # Wait for the analysis to be completed
      - |
        while [ $(jq -r '.task.status' status.json) = IN_PROGRESS ] || [ $(jq -r '.task.status' status.json) = PENDING ] ;
        do
          curl -s -u "$SONAR_TOKEN:" $SONAR_HOST/api/ce/task?id=$cetaskid > status.json ;
          export END=$(date +%s)
          export ANALYSISTIME=$((END-START))
          if [ $ANALYSISTIME -gt 600 ] ; then
            export CODEBUILD_BUILD_SUCCEEDING=0 ;
            break ;
          fi
        done
      # If analysis is taking longer time, build will fail. Default timeout is set to 600 seconds. Please change if required.
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then 
          echo "Analysis taking longer than usual time. Default value is set to 600s. Please verify." ;
          exit 1; 
        fi
      # Once the analysis is completed, verifying the status success or failed. Build exits if failed.
      - |
        if [ $(jq -r '.task.status' status.json) = SUCCESS ] ; then
          export analysisid=$(jq -r '.task.analysisId' status.json) ;
        elif [ $(jq -r '.task.status' status.json) = FAILED ] ; then
          export CODEBUILD_BUILD_SUCCEEDING=0 ;
        fi
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then 
          echo "Analysis Failed in the sonar server. Please verify in the server." ;
          exit 1; 
        fi
      # Quality gate status 
      - curl -u "$SONAR_TOKEN:" $SONAR_HOST/api/qualitygates/project_status?analysisId=$analysisid > result.json
      - cat result.json
      # Quality scan validation. Build will fail for all enviroments other than Dev if ERROR/WARN found. Build will fail if QG is not attached.
      - |
        if [ $(jq -r '.projectStatus.status' result.json) != OK ] && [ $APP_ENVIRONMENT != "DEV" ] ; then
          echo "ERROR/WARN found or there's no QG attached in the Sonar server. Please verify" ;
          export CODEBUILD_BUILD_SUCCEEDING=0 ;
        elif [ $(jq -r '.projectStatus.status' result.json) = None ] ; then 
          echo "There is no QG is attached. Please verify" ;
          export CODEBUILD_BUILD_SUCCEEDING=0 ;
        fi

  post_build:
    commands:  
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then 
            echo "Quality gate status is not success - exiting with error"
            echo " **** check your application vulnerabilities and coverage here - $SONAR_HOST"
            exit 1; 
        else
          echo 'Build Success'
        fi
artifacts:
    files:
      - '**/*'    

cache:
  paths:
  - '/root/.npm/**/*'
