version: 0.2
env:
  shell: bash
  parameter-store:
    GITHUB_TOKEN: MRAD_GITHUB_TOKEN
phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com".insteadOf "https://github.com"
      - env | sort
      - aws sts get-caller-identity
      - pwd
      - ls -al
      - node --version
      - npm config set audit false
      - npm config set fund false
      - npm --version
      - aws --version
      - touch stack-names.json
      - npm install
      - NODE_TLS_REJECT_UNAUTHORIZED=0 node src/orchestrator/get-last-seq-id.js
      - aws s3 cp ./last-seq-id s3://$PIPELINE_BUCKET/
      - aws s3 rm s3://$PIPELINE_BUCKET/seeds/ --recursive
      - aws s3 rm s3://$PIPELINE_BUCKET/edges/ --recursive
      - aws s3 rm s3://$PIPELINE_BUCKET/vertices/ --recursive
artifacts:
  files:
    - stack-names.json
