version: 0.2
env:
  variables:
    NODE_OPTIONS: --max-old-space-size=12500
  shell: bash
  parameter-store:
    GITHUB_TOKEN: MRAD_GITHUB_TOKEN
phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - pwd
      - ls -al
      - /bin/bash ./buildspecs/buildspec-tfc-seed.sh
