# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.

version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - PROJECT_NAME
    - SONAR_HOST
    - PROJECT_ROOT_DIRECTORY
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    SONAR_TOKEN            : "${SONAR_TOKEN}"
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH   : "${GIT_REPO_BRANCH}"
    UNIT_TEST_COMMANDS : "${UNIT_TEST_COMMANDS}"
phases:
  install:
    runtime-versions:
      python: $PYTHON_RUNTIME
    commands:
      - echo "Entered the install phase..."      
      - echo "Installing Sonar Scanner CLI"
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip && rm -rf sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=sonar-scanner-5.0.1.3006-linux/bin:$PATH
      - echo "verifying sonar-scanner cli installation" && sonar-scanner -h

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure python is installed"
      - echo "python version is `python --version`" && echo "pip version is `pip --version`"
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the Build phase..."
      - echo Build started on `date`
      - echo `pwd`
      - ls -lart
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo `pwd`
      - ls -lart
      # verifying environment_variables
      - echo "PROJECT_NAME - $PROJECT_NAME"
      #refactoring $ARTIFACTORY_HOST without https
      - REFACTORED_ARTIFACTORY_HOST=$(echo $ARTIFACTORY_HOST | cut -d'/' -f3 | cut -d':' -f1)
      - echo "artifactory host without https is $REFACTORED_ARTIFACTORY_HOST"

      #installing virtualenv and activating it
      - echo "installing and activating virtualenv"
      - python -m pip install virtualenv
      - python -m virtualenv webapp
      - . webapp/bin/activate
      # pip.conf update to virtualenv
      - |
        if [[ ! -f webapp/pip.conf ]]; then
           echo "updating pip.conf to artifactory"
           echo [global] >> webapp/pip.conf
           echo index-url = https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@$REFACTORED_ARTIFACTORY_HOST/artifactory/api/pypi/$ARTIFACTORY_REPO_KEY/simple >> webapp/pip.conf
        fi
      # installing required pip dependencies
      - pip install -r requirements.txt

      #running Unit tests
      - echo "running unit tests with following command $UNIT_TEST_COMMANDS"
      - eval $UNIT_TEST_COMMANDS
      #running sonar analysis
      - echo "Running Sonar Analysis"
      - export PATH=$CODEBUILD_SRC_DIR/sonar-scanner-5.0.1.3006-linux/bin:$PATH
      - sonar-scanner -D sonar.projectKey="$PROJECT_KEY" -D sonar.projectName="$PROJECT_NAME" -D sonar.branch.name="$GIT_REPO_BRANCH" -D sonar.token="$SONAR_TOKEN" -D sonar.host.url="$SONAR_HOST"
      # checking quality gate status
      - sleep 30
      - echo "checking SonarQube Quality Gate Status"
      - curl -s -u "$SONAR_TOKEN:" -G --data-urlencode "branch=$GIT_REPO_BRANCH" --data-urlencode "projectKey=$PROJECT_KEY"  "$SONAR_HOST"/api/qualitygates/project_status > result.json
      - cat result.json
      - |
        if [ $(jq -r '.projectStatus.status' result.json) != OK ] ; then
           echo "Quality gate status is not success - exiting with error"
           echo " **** check your application vulnerabilities and coverage here - $SONAR_HOST"
           exit 1
        fi
artifacts:
    files:
      - '**/*'


#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.cache/pip/**/*'