# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - DEPENDENCY_FILES_LOCATION
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    # GIT_REPO_BRANCH   : "${GIT_REPO_BRANCH}"
    # GIT_REPO_URL      : "${GIT_REPO_URL}"
phases:
  install:
    runtime-versions:
      java: $JAVA_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure Java is installed"
      - echo `java -version`
      - echo "Making sure Maven is installed"
      - echo `mvn --version`
      # - echo "CCOE-3824 - Making sure GIT cli is installed"
      # - echo `git --version`
      - echo "Making sure JFROG cli is installed"
      - echo `jf --version`
  build:
    on-failure: ABORT
    commands:
      - |
        if [ "$DOWNLOAD_ARTIFACT" = "false" ] ; then
          echo "if download artifact is false then, this stage shouldn't be created. exiting the build, reverify your pipeline variables"
          exit 1;
        else
          echo "Entered the build phase execution..."
          echo Build started on `date`
        fi
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi

      - echo "ARTIFACTORY_REPO_KEY - $ARTIFACTORY_REPO_KEY"
      - echo "ARTIFACTORY_AUTH_PREFIX - $ARTIFACTORY_AUTH_PREFIX"
      - echo "ARTIFACTORY_USER - $ARTIFACTORY_USER"

      - jf c add "$SERVER_ID" --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST" --interactive=false
      - jf c s
      - jf rt ping
      
      - |
        if [ ! -f "version.toml" ] ; then
          echo "***version.toml does not exist, create version.toml and rerun the pipeline***"
          exit 1;
        else
          echo "**** version.toml exists, getting values of group_id and artifact_id from version.toml ****"
          ARTIFACT_GROUPID=$(cat version.toml | grep group_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          VERSION=$(cat version.toml | grep version | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_ID=$(cat version.toml | grep artifact_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_NAME=$(cat version.toml | grep artifact_name | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          POM=$(cat version.toml | grep pom | cut -d'=' -f2 | tr -d ' ' | tr -d '"')

          echo "pom to be downloaded is $POM"
          echo "artifact to be downloaded is $ARTIFACT_NAME"
    
        fi

      - ARTIFACT_PATH=$ARTIFACT_GROUPID/$ARTIFACT_ID/$VERSION

      - echo "artifact to be downloaded is $ARTIFACT_NAME from path $ARTIFACTORY_REPO_KEY/$ARTIFACT_PATH with properties validating with branch=$SONAR_BRANCH_SCANNED"
      - |
        set -e
        jf rt dl --props branch=$SONAR_BRANCH_SCANNED $ARTIFACTORY_REPO_KEY/$ARTIFACT_PATH/$ARTIFACT_NAME --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST/artifactory" 
      - ls -la
      - ls -la $ARTIFACT_PATH/$ARTIFACT_NAME
      - echo "downloading POM file"
      - jf rt dl $ARTIFACTORY_REPO_KEY/$ARTIFACT_PATH/$POM --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST/artifactory"
      - ls -la $ARTIFACT_PATH/$POM
      - mkdir -p target && cp -pr $ARTIFACT_PATH/$ARTIFACT_NAME target/ && cp $ARTIFACT_PATH/$POM target/
      - ls -la target/
      
  post_build:
    commands:
      - echo "only required if appspec.yml exists other than root directory"
      - find . -type f -name "appspec.yml" -exec cp {} $CODEBUILD_SRC_DIR/ \; || true
      - echo "verifying appspec.yml" && ls $CODEBUILD_SRC_DIR/appspec.yml || true

artifacts:
    files:
      - '**/*'

#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.m2/**/*'