// Package rules defines the control catalog and enforceable rule set derived
// from PG&E's "AI-DLC UCF Controls Worksheet" — the authoritative mapping of
// the Unified Controls Framework (app-applicable NIST 800-53 subset) to the
// AI-DLC constitution.
//
// The worksheet catalogs 69 app-applicable controls with their canonical NIST
// IDs, the AI-DLC program disposition ("Coverage": Done/Advise/Verify/…), and a
// per-control narrative (who owns it, the action required, developer advice,
// and clarifying notes). This package encodes ALL 69 so every report accounts
// for the full framework. Each control carries a Class:
//
//   - ClassCode        — a code/IaC rule evaluates it (15 controls; see
//     rules_impl.go). Produces PASS/PARTIAL/FAIL/N/A.
//   - ClassManual      — a real control that only human/runtime attestation can
//     confirm (personnel, process, pen tests). Auto-MANUAL.
//   - ClassUnspecified — the framework/worksheet gives no evaluable criterion
//     (deferred: "Future"/"Cyber to Define"). Auto-MANUAL with a distinct note.
//
// This makes coverage honest: the report shows all 69 controls and exactly
// which a machine can and cannot judge — never silently omitting the controls
// that are not repo-checkable.
//
// CANONICAL IDs: this catalog supersedes the earlier degraded-PDF extraction,
// whose control names were shifted one control down (e.g. it keyed account
// lockout to AC-06; the worksheet's canonical ID is AC-07, and AC-06 is Least
// Privilege). Finding IDs therefore changed with this migration — see the
// workspace charter (compliance-reviewer.md) for the old→new remap.
package rules

import "github.com/pgetech/epic-compliance/internal/model"

// SpecSource identifies the steering doc this catalog is derived from.
const SpecSource = "AI-DLC UCF Controls Worksheet (Unified Controls Framework, app-applicable)"

// sev is a small helper for baseline lists.
func sev(s ...model.Severity) []model.Severity { return s }

var (
	bHML = sev(model.SeverityHigh, model.SeverityMedium, model.SeverityLow)
	bHM  = sev(model.SeverityHigh, model.SeverityMedium)
	bH   = sev(model.SeverityHigh)
	bMH  = sev(model.SeverityMedium, model.SeverityHigh)
)

// Controls is the full catalog of all 69 app-applicable controls.
var Controls = map[string]model.Control{
	// ===== CODE-CHECKABLE controls (15) — evaluated by rules in rules_impl.go =====
	"AC-02-04": {NISTID: "AC-02-04", Title: "Audit Account Actions (creation, modification, enable, disable, removal)",
		Requirement: "Automatically audit account creation, modification, enabling, disabling, and removal actions.",
		Baseline:    bHM, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "AI-DLC needs to enforce this. If the application is management its own accounts, then it must use AWS Cloud Trail to ensure account auditing is occuring.",
		Advice:      "Developers are to use standard Account Management tools, Active Directory or LDAP.",
		Notes:       "Anytime an account is created or removed, it must be audited",
	},
	"AC-03-00": {NISTID: "AC-03-00", Title: "Access Enforcement",
		Requirement: "Enforce approved authorizations for logical access in accordance with access control policies; deny by default; enforce server-side.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "N/A",
		Advice:      "Use standards for IAM. Active Directory, LDAP.",
		Notes:       "Outside of AI-DLC.",
	},
	"AC-07-00": {NISTID: "AC-07-00", Title: "Unsuccessful Logon Attempts (lockout after 10 attempts in 60 min)",
		Requirement: "Enforce a limit of no more than 10 consecutive invalid logon attempts by a user during any 60-minute period; automatically lock the account/node for at least 15 minutes when the maximum is exceeded.",
		Baseline:    bHM, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "If the application is handling authentication, then it must implement a lockout after 10 bad attempts within 60 minutes",
		Advice:      "Guidance to use standard application authetication via AD with entra ID or LDAP.",
	},
	"AC-08-00": {NISTID: "AC-08-00", Title: "System Use Notification (login banner)",
		Requirement: "Display a system-use notification banner before granting access, stating: users are accessing a PG&E system; usage may be monitored/recorded/audited; unauthorized use is prohibited; use indicates consent to monitoring.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Required",
		Action:      "AI-DLC needs to implement this with the required language for the Banner as part of UI/UX standard.",
		Notes:       "Inherited from your workstation. This is a login banner.",
	},
	"AC-10-00": {NISTID: "AC-10-00", Title: "Concurrent Session Control (max 2 sessions)",
		Requirement: "Limit the number of concurrent sessions for all individual and shared accounts to two.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassCode,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Required - Output application needs to have session controls built-in, if possible. If not technically capable in the application, the responsibility goes to the functional area managing the system in production to enable session controls at the server level.",
		Action:      "AI-DLC needs to implement instructions to enforce this.",
		Notes:       "One user can only have two open sessions concurrently.",
	},
	"AU-03-00": {NISTID: "AU-03-00", Title: "Content of Audit Records",
		Requirement: "Ensure audit records establish: (a) what type of event occurred, (b) when, (c) where, (d) source of the event, (e) outcome, and (f) identity of any individual associated with the event.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Done", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Action:      "AI-DLC has this already",
		Notes:       "AU-03 is about the content of the logs.",
	},
	"AU-08-00": {NISTID: "AU-08-00", Title: "Time Stamps",
		Requirement: "Use internal system clocks to generate UTC-based time stamps for audit records; synchronize to enterprise reference clocks where available.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Action:      "Time stamps need to be included in AI-DLC. This wouid be part of the log creation.",
		Advice:      "Guidance to use CloudWatch Logs.",
	},
	"AU-10-00": {NISTID: "AU-10-00", Title: "Non-repudiation",
		Requirement: "Protect against an individual falsely denying having performed an action (non-repudiation): attribute logged actions to the responsible identity with a trustworthy timestamp.",
		Baseline:    bH, AppApplicability: "Maybe", Class: model.ClassCode,
		Coverage: "", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Notes:       "Ensures the log is the one created by the system. This is not fully defined by PG&E yet.",
	},
	"AU-12-00": {NISTID: "AU-12-00", Title: "Audit Record Generation",
		Requirement: "Provide audit record generation for the security-relevant event types the system is capable of logging: authentication events, authorization grants/denials, privilege escalation, and configuration changes.",
		Baseline:    bMH, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Done", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Action:      "AI-DLC already does this at the code level and application level.",
		Notes:       "Currently happening in AI-DLC at the code level and the application level.",
	},
	"CM-06-00": {NISTID: "CM-06-00", Title: "Configuration Settings (most restrictive mode)",
		Requirement: "Configure the system to the most restrictive mode consistent with operational requirements; apply and enforce a secure baseline configuration (STIG/CIS).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Required",
		Action:      "Create Requirement Traceability Matrix",
		Advice:      "Advise developers to use secure coding practices. Harden the application to the exdtent possible.",
		Notes:       "Configuration settings is variable based on the scope of the application. Application owner is to define what is required within the application.",
	},
	"CM-07-00": {NISTID: "CM-07-00", Title: "Least Functionality (minimum required functions)",
		Requirement: "Configure the system for least functionality; disable/restrict unneeded ports, protocols, and services.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Verify", Mandatory: true,
		Disposition: "Required",
		Action:      "Code Reviewer needs to check for least functionality.",
	},
	"IA-02-00": {NISTID: "IA-02-00", Title: "Organizational Users (unique ID + authentication)",
		Requirement: "Uniquely identify and authenticate organizational users and associate that identity with processes acting on behalf of those users.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "The application would have to enforce the use of uniqueness for IDs and not shared IDs. If it has the capability of doing its own authentication creation or usage.",
	},
	"SA-10-01": {NISTID: "SA-10-01", Title: "Software and Firmware Integrity Verification",
		Requirement: "Verify the integrity of software and firmware components (e.g. signature/HMAC/checksum verification) as part of trusted generation and distribution.",
		Baseline:    bHM, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
	},
	"SC-08-00": {NISTID: "SC-08-00", Title: "Transmission Confidentiality and Integrity",
		Requirement: "Protect the confidentiality and integrity of transmitted information (TLS 1.2+ in transit).",
		Baseline:    bHM, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "Verify", Mandatory: true,
		Disposition: "Contingent - This generally applies to the system where the application resides and the communicationsbetween systems; however, a web application should be covered under TLS settings already.",
		Action:      "Verify that AI-DLC is doing this correctly.",
		Advice:      "The agent should never recommend to remove encryption",
		Notes:       "All data transfers must use encryption",
	},
	"SC-28-00": {NISTID: "SC-28-00", Title: "Protection of Information at Rest",
		Requirement: "Protect the confidentiality and integrity of information at rest (encryption at rest).",
		Baseline:    bHM, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a system requirement where the coded application resides.",
		Advice:      "Advise developers to use standard storage infrastructure and not use locally application-managed storage.",
		Notes:       "Any data stored at rest (including configuration files) must have encryption.",
	},

	// ===== EPIC-ADDED control (beyond the worksheet's 69) =====
	// The AI-DLC UCF worksheet contains no secrets/authenticator-management
	// control (verified: no IA-05 / secret / credential / key-management row).
	// For app-code review, committed secrets are the highest-signal defect a
	// gate can catch, so EPIC enforces one anyway, keyed to the real NIST id for
	// Authenticator Management (IA-05). Flagged AddedByEPIC so reports/coverage
	// stay honest that this is not one of the 69 worksheet controls.
	"IA-05-00": {NISTID: "IA-05-00", Title: "Authenticator Management (no committed secrets)",
		Requirement: "Do not commit secrets, credentials, private keys, or high-entropy tokens to source control. Manage authenticators via a secrets manager / Key Vault, injected at runtime.",
		Baseline:    bH, AppApplicability: "Yes", Class: model.ClassCode,
		Coverage: "", Mandatory: true, AddedByEPIC: true,
		Disposition: "Required - EPIC-enforced. Not in the AI-DLC UCF worksheet; added because committed secrets are a critical, greppable app-code defect the gate must block.",
		Action:      "Scan the repository for committed secrets/keys/tokens and hard-fail on any real match.",
		Advice:      "Store secrets in AWS Secrets Manager / Azure Key Vault and inject at runtime; never commit .env with real values, tfstate, private keys, or hardcoded tokens.",
		Notes:       "Covers hardcoded credentials, committed .env/tfstate secrets, private-key files, and cloud/provider access keys.",
	},

	// ===== MANUAL controls — human/runtime attestation required =====
	"AC-02-03": {NISTID: "AC-02-03", Title: "Disable Accounts (inactive 60 days)",
		Requirement: "Disable Accounts (inactive 60 days).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "AI-DLC needs to enforce this.",
		Notes:       "Requirement is to expire accounts under the specified conditions. Developer needs to be aware of how the application is accessed.",
	},
	"AC-02-05": {NISTID: "AC-02-05", Title: "Inactivity Logout",
		Requirement: "Inactivity Logout.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "AI-DLC needs to implement this.",
		Notes:       "Difference between an inactivity lockout and a session lockout.",
	},
	"AC-02-11": {NISTID: "AC-02-11", Title: "Usage Conditions / Atypical Usage Monitoring",
		Requirement: "Usage Conditions / Atypical Usage Monitoring.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - Applies to the output applications production implementation; e.g., what server the application lives on and what the functional area considers atypical use.",
		Action:      "N/A",
		Advice:      "Developers are to use standard auditing and logging frameworks",
		Notes:       "This is implemented in our FinOps. Out-of-scope for AI-DLC.",
	},
	"AC-02-12": {NISTID: "AC-02-12", Title: "Monitoring for Atypical Usage",
		Requirement: "Monitoring for Atypical Usage.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - Applies to the output applications production implementation; e.g., what server the application lives on and what the functional area considers atypical use.",
		Action:      "N/A",
		Advice:      "Application owners are to ensure that outputs to the Red Button process are implemented as required.",
		Notes:       "Compliance has a \"red button process\" already defined. The application needs to output into the Red Button process.",
	},
	"AC-02-13": {NISTID: "AC-02-13", Title: "Disable Accounts for High-Risk Individuals (within 24 hours)",
		Requirement: "Disable Accounts for High-Risk Individuals (within 24 hours).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "If the application is doing its own account manager, the it needs to have the ability to disable accounts within 24 hours.",
		Advice:      "Developers are to use standard Active Directory (AD) or LDAP, and should not do their own account management.",
	},
	"AC-05-00": {NISTID: "AC-05-00", Title: "Separation of Duties",
		Requirement: "Separation of Duties.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Done", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "Already implemented. If the application is handling authorization, the read permissions must be separate from the write permissions",
		Advice:      "Guidance to use standard application authorization via AWS IAM and AD with entra ID, as opposed to custom builds.",
		Notes:       "Checks at architecture design level and code generation level",
	},
	"AC-06-00": {NISTID: "AC-06-00", Title: "Least Privilege",
		Requirement: "Least Privilege.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Done", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "Already implemented. Requires a direct mapping of permissions to resources. No use of wildcards. Separate policy statements for read and write to resources.",
		Advice:      "Guidance to use standard application authorization via AWS IAM and AD with entra ID, as opposed to custom builds.",
		Notes:       "Instructions are already implemented within AI-DLC",
	},
	"AC-11-00": {NISTID: "AC-11-00", Title: "Session Lock / Termination",
		Requirement: "Session Lock / Termination.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Done", Mandatory: true,
		Disposition: "Required - Output application needs to have session controls built-in, if possible. If not technically capable in the application, the responsibility goes to the functional area managing the system in production to enable session controls at the server level.",
		Action:      "AI-DLC already does this.",
		Notes:       "AI-DLC writes code that implements this,",
	},
	"AC-12-00": {NISTID: "AC-12-00", Title: "Session Termination",
		Requirement: "Session Termination.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Done", Mandatory: true,
		Disposition: "Required - Output application needs to have session controls built-in, if possible. If not technically capable in the application, the responsibility goes to the functional area managing the system in production to enable session controls at the server level.",
		Action:      "AI-DLC already does this.",
	},
	"AC-17-00": {NISTID: "AC-17-00", Title: "Remote Access",
		Requirement: "Remote Access.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Required - Output application has to use authorized connections using TLS.",
		Action:      "AI-DLC needs to check if application is specifying TLS 1.2 or above. Cyber needs to review this.",
		Notes:       "In-transit encryption must use TLS 1.2",
	},
	"AU-03-03": {NISTID: "AU-03-03", Title: "Identifiable Information Elements in Audit Records",
		Requirement: "Identifiable Information Elements in Audit Records.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Verify", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Action:      "Need to verify what AI-DLC is outputting. Identifiable information should not be in any output to a log or otherwise",
		Notes:       "Defined PII is not covered. This is a planned control and not fully implemented within PG&E yet. Just need to verify what is being putputted to the logs.",
	},
	"AU-05-00": {NISTID: "AU-05-00", Title: "Response to Audit Logging Failures",
		Requirement: "Response to Audit Logging Failures.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Verify", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Action:      "Steering to check which backend monitoring systems are in use. If none are defined, then steering should add audit-logging failure into the application.",
		Notes:       "Outside of AI-DLC. This function is normally taken care of by the monitoring and logging.",
	},
	"AU-06-00": {NISTID: "AU-06-00", Title: "Audit Record Review and Reporting (weekly)",
		Requirement: "Audit Record Review and Reporting (weekly).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Required - Output application logs have to adhere to standard and contain all the required information, where capable.",
		Notes:       "Not handled by AI-DLC. Out of scope for AI-DLC.",
	},
	"CA-08-00": {NISTID: "CA-08-00", Title: "Penetration Testing (annual, restricted/regulatory data or external-facing)",
		Requirement: "Penetration Testing (annual, restricted/regulatory data or external-facing).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Advice:      "Guidance is to use the Penetration Testing tools standard. Tols are to be integrated within the CICD pipeline. This is outside of the AI-DLC process.",
		Notes:       "AI-DLC writes the test cases but does not execute the penetration test.",
	},
	"CA-09-00": {NISTID: "CA-09-00", Title: "Internal System Connections",
		Requirement: "Internal System Connections.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Verify", Mandatory: true,
		Disposition: "N/A - The system where the application is deployed would have to implementthis.",
		Action:      "Verify that AI-DLC is doing this correctly.",
		Notes:       "AI-DLC is doing this. Need to verify AI-DLC is doing it correctly.",
	},
	"CM-03-00": {NISTID: "CM-03-00", Title: "Configuration Change Control (CAB monthly)",
		Requirement: "Configuration Change Control (CAB monthly).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Document", Mandatory: true,
		Disposition: "Required - Prior to code deployment or change.",
		Action:      "AI-DLC should produce a document to aid in the human review process.",
	},
	"CM-04-00": {NISTID: "CM-04-00", Title: "Impact Analysis (security/privacy before change)",
		Requirement: "Impact Analysis (security/privacy before change).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Action:      "AI-DLC specifies a human in the loop prior to deployment.",
		Advice:      "Developers are required to follow our change management process and to use our CICD pipeline for changes and deployments.",
	},
	"CM-05-00": {NISTID: "CM-05-00", Title: "Access Restrictions for Change",
		Requirement: "Access Restrictions for Change.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - The system where the application is deployed would have to implement this.",
		Advice:      "Deployments are required to follow our change management process and to use our CICD pipeline for changes and deployments.",
		Notes:       "The developer and the deployment approval cannot be the same person.",
	},
	"CM-08-00": {NISTID: "CM-08-00", Title: "System Component Inventory",
		Requirement: "System Component Inventory.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "Document", Mandatory: true,
		Disposition: "N/A - The output application would become an inventory item on the system inventory where it will be residing.",
		Action:      "We can template the list. AI-DLC's configuration files should be in the inventory",
	},
	"CM-09-00": {NISTID: "CM-09-00", Title: "Configuration Management Plan",
		Requirement: "Configuration Management Plan.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Done", Mandatory: true,
		Disposition: "N/A - The output application owner would need to create this in their documentation.",
		Action:      "AI-DLC enforces Terraform standards.",
	},
	"CP-02-00": {NISTID: "CP-02-00", Title: "Contingency Plan",
		Requirement: "Contingency Plan.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - The output application owner would need to create this in their documentation.",
		Advice:      "Not applicable to AI-DLC",
	},
	"CP-04-00": {NISTID: "CP-04-00", Title: "Contingency Plan Testing (annual)",
		Requirement: "Contingency Plan Testing (annual).",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - The output application owner would need to create this in their documentation.",
		Advice:      "Not applicable to AI-DLC",
	},
	"CP-10-00": {NISTID: "CP-10-00", Title: "System Recovery and Reconstitution",
		Requirement: "System Recovery and Reconstitution.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - The output application owner would need to create this in their documentation.",
		Advice:      "Not applicable to AI-DLC",
	},
	"IA-08-00": {NISTID: "IA-08-00", Title: "Non-Organizational Users",
		Requirement: "Non-Organizational Users.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Advice:      "Advise to enforce authentication at all entry points into the application. No back doors.",
	},
	"IA-11-00": {NISTID: "IA-11-00", Title: "Re-Authentication",
		Requirement: "Re-Authentication.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Contigent - If output application has local access configured this is required. - If no local access I being coded or configured, this would be inherited from the identity management system being used.",
		Action:      "Enforce our standard as AD",
		Advice:      "Guidance is to use the IAM standard, Active Directory or LDAP.",
		Notes:       "Check that these triggers apply to the steering documents and code reviewer. Generally, this is handled outside of the application. The authentication mechanism would enforce a re-authentication.",
	},
	"IA-12-00": {NISTID: "IA-12-00", Title: "Identity Proofing",
		Requirement: "Identity Proofing.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Advice:      "Handled at the enterprise level. Not applicable to the code reviewer and framework.",
	},
	"MP-02-00": {NISTID: "MP-02-00", Title: "Media Access",
		Requirement: "Media Access.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - The system where the application is deployed would have to implement this.",
	},
	"PL-02-00": {NISTID: "PL-02-00", Title: "System Security and Privacy Plans",
		Requirement: "System Security and Privacy Plans.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "N/A - The output application owner would need to create this in their documentation.",
	},
	"PS-04-00": {NISTID: "PS-04-00", Title: "Personnel Termination",
		Requirement: "Personnel Termination.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
	},
	"PS-05-00": {NISTID: "PS-05-00", Title: "Personnel Transfer",
		Requirement: "Personnel Transfer.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
	},
	"RA-03-00": {NISTID: "RA-03-00", Title: "Risk Assessment",
		Requirement: "Risk Assessment.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
	},
	"RA-05-00": {NISTID: "RA-05-00", Title: "Vulnerability Monitoring and Scanning (every 90 days)",
		Requirement: "Vulnerability Monitoring and Scanning (every 90 days).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Advice:      "Guidance is to use standards. GitHub, CICD Pipeline, Wiz, etc",
		Notes:       "Every 90-days: Once per quarter every system is scanned. Scanning is of systems and assets, not of the code.",
	},
	"RA-07-00": {NISTID: "RA-07-00", Title: "Risk Response",
		Requirement: "Risk Response.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
	},
	"RA-08-00": {NISTID: "RA-08-00", Title: "Privacy Impact Assessments",
		Requirement: "Privacy Impact Assessments.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "Verify", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Action:      "Ai-DLC to verify that PII is tagged in accordance with PG&E standards",
		Notes:       "AI-DLC doesn't need to ask the questions about PII, but AIDLC does need to make sure PII is tagged.",
	},
	"SA-10-00": {NISTID: "SA-10-00", Title: "Developer Configuration Management",
		Requirement: "Developer Configuration Management.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
		Advice:      "Developers (and the application) are requied to use our CICD tools and follow the standard Change Management process",
	},
	"SA-10-02": {NISTID: "SA-10-02", Title: "Configuration Management Processes",
		Requirement: "Configuration Management Processes.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
		Advice:      "The system is advised to use our standard CICD and pipeline.",
	},
	"SA-10-04": {NISTID: "SA-10-04", Title: "Trusted Generation",
		Requirement: "Trusted Generation.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
	},
	"SA-10-05": {NISTID: "SA-10-05", Title: "Mapping Integrity for Version Control",
		Requirement: "Mapping Integrity for Version Control.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
	},
	"SA-10-06": {NISTID: "SA-10-06", Title: "Trusted Distribution",
		Requirement: "Trusted Distribution.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
	},
	"SA-11-00": {NISTID: "SA-11-00", Title: "Developer Testing and Evaluation",
		Requirement: "Developer Testing and Evaluation.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
	},
	"SA-17-00": {NISTID: "SA-17-00", Title: "Developer Security and Privacy Architecture",
		Requirement: "Developer Security and Privacy Architecture.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
	},
	"SA-21-00": {NISTID: "SA-21-00", Title: "Developer Screening",
		Requirement: "Developer Screening.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not in the output application. The training data needs to be protected and control needs to be applied for deployment of any code.",
		Advice:      "Vendors must use the AI-DLC checklist to verify they are ready to develop and go through TSR",
		Notes:       "Internal developers are automatically covered and meet this requirement",
	},
	"SC-10-00": {NISTID: "SC-10-00", Title: "Network Disconnect (20-minute inactivity)",
		Requirement: "Network Disconnect (20-minute inactivity).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Advice:      "If the application is managing its own session, then its idle session timeout must be set to 20 minutes.",
		Notes:       "Maximum Inactive Session Time is 20 minutes.",
	},
	"SI-02-00": {NISTID: "SI-02-00", Title: "Flaw Remediation",
		Requirement: "Flaw Remediation.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Note: This is required for AI DLC on the backend, not the application output. This should be occurring well in advance of production release.",
		Advice:      "External (In CICD Pipeline) code reviewer must log its reports to Cyber. Ideal: integrate findings with Brinqa.",
	},
	"SI-03-00": {NISTID: "SI-03-00", Title: "Malicious Code Protection",
		Requirement: "Malicious Code Protection.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This comes from the system where the application resides.",
		Advice:      "Developers are to use GitHub, our CICD pipeline, and code scanning tools",
		Notes:       "Wiz (by design) scans GitHub repositories every 90 days or more frequently.",
	},
	"SI-04-00": {NISTID: "SI-04-00", Title: "System Monitoring",
		Requirement: "System Monitoring.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This is a PG&E functional activity.",
		Advice:      "Developers are to use standard deployment targets, such as AWS and Azure.",
		Notes:       "Standard tools, incl AWS Guard Duty, automatically ship their logs to SIOC.",
	},
	"SI-12-00": {NISTID: "SI-12-00", Title: "Information Management and Retention",
		Requirement: "Information Management and Retention.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This comes from the system where the application resides.",
		Advice:      "If the application is managing its own logs, then it should be deploying them to our SIEM, Q-Radar.",
	},
	"SR-05-02": {NISTID: "SR-05-02", Title: "Acceptance, Modification, or Update Assessment",
		Requirement: "Acceptance, Modification, or Update Assessment.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "Advise", Mandatory: true,
		Disposition: "Inherited - This applies to the front end processes before AI DLC is even engaged or at the system level.",
		Action:      "AI-DLC to only download files from JFrog. And if file not avialable in JFrog to download via proxy (real-time) rather than going outside of JFrog.",
		Advice:      "Developer to only use JFrog to access software downloads and to download new files not in the library.",
	},
	"SR-06-00": {NISTID: "SR-06-00", Title: "Supplier Assessments and Reviews (every 3 years)",
		Requirement: "Supplier Assessments and Reviews (every 3 years).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This applies to the front end processes before AI DLC is even engaged or at the system level.",
		Advice:      "Developer to be retrained and re-checked via our checklist every three years and follow the TSR process.",
	},
	"SR-09-01": {NISTID: "SR-09-01", Title: "Anti-Tamper (Life Cycle)",
		Requirement: "Anti-Tamper (Life Cycle).",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassManual,
		Coverage: "", Mandatory: true,
		Disposition: "Inherited - This applies to the front end processes before AI DLC is even engaged or at the system level.",
		Advice:      "Developers are to use our standard tools, CICD pipeline, and scanning tools; and verify that our quality gates are in place and operating.",
	},

	// ===== UNSPECIFIED controls — framework gives no machine-evaluable criterion =====
	"SI-12-01": {NISTID: "SI-12-01", Title: "Limit PII Elements",
		Requirement: "Limit PII Elements.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassUnspecified,
		Coverage: "Cyber to Define", Mandatory: false,
		Disposition: "N/A - Undefined criteria in control.",
		Action:      "Nothing to do now. Future control.",
		Notes:       "Future TODO, once PII Elements have been identified by Cyber",
	},
	"SI-12-02": {NISTID: "SI-12-02", Title: "PII Minimization for Research/Testing/Training",
		Requirement: "PII Minimization for Research/Testing/Training.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassUnspecified,
		Coverage: "Future", Mandatory: false,
		Disposition: "N/A - Undefined criteria in control.",
		Action:      "Nothing to do now. Future control.",
		Notes:       "Future TODO, once PII Elements have been identified by Cyber",
	},
	"SI-12-03": {NISTID: "SI-12-03", Title: "Information Disposal",
		Requirement: "Information Disposal.",
		Baseline:    bHML, AppApplicability: "Yes", Class: model.ClassUnspecified,
		Coverage: "Future", Mandatory: false,
		Disposition: "N/A - Undefined criteria in control.",
		Action:      "Nothing to do now. Future control.",
		Notes:       "Future TODO, once PII Elements have been identified by Cyber",
	},
	"SI-19-00": {NISTID: "SI-19-00", Title: "De-identification",
		Requirement: "De-identification.",
		Baseline:    bHML, AppApplicability: "Maybe", Class: model.ClassUnspecified,
		Coverage: "Future", Mandatory: false,
		Disposition: "N/A - Undefined criteria in control.",
		Action:      "Nothing to do now. Future control.",
		Notes:       "Future TODO, once PII Elements have been identified by Cyber",
	},
}
