jobs:
- job: DeployJob
  displayName: "Deploy App"
  pool:
    vmImage: ubuntu-latest
    
  workspace:
    clean: all

  #############################################################################
  # Steps
  #############################################################################
  steps:

    ###########################################################################
    # Download App Artifact
    ###########################################################################
    - task: DownloadPipelineArtifact@2
      displayName: "Download app artifact"
      inputs:
        artifactName: epic-build
        targetPath: "$(System.DefaultWorkingDirectory)/${{ parameters.appName }}/${{ parameters.codePath }}/.build"


    ###########################################################################
    # Deploy - HTML (static), Angular (node)
    ###########################################################################
    - ${{ if or(eq(parameters.appType, 'html'), eq(parameters.appType, 'angular')) }}:
      - template: basic/main.yml
        parameters:
          ${{ insert }}: ${{ parameters }}


    ###########################################################################
    # Deploy - .NET, Python
    ###########################################################################
    - ${{ if and(ne(parameters.appType, 'html'), ne(parameters.appType, 'angular')) }}:
      - template: ${{ parameters.appType }}/main.yml
        parameters:
          ${{ insert }}: ${{ parameters }}
