version: 0.2
env:
  variables:
    REPO: ${repo_name}
  secrets-manager:
    GITHUB_TOKEN: "MRAD_GITHUB_TOKEN:github"
phases:
  install:
    runtime-versions:
      # vars with curly braces are replaced by terraform, not codepipeline
      nodejs: ${node_version}
    commands:
      - env | sort
      - pwd
      # buildspec-code.sh is located in the target repo, not the webcore-pipelines repo
      # https://github.com/PGEDigitalCatalyst/Engage-Webapp/blob/dev/buildspecs/buildspec-code.sh
      - /bin/bash ./buildspecs/buildspec-code.sh
artifacts:
  files:
    - "**/*"
