# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    LAMBDA_FUNCTION_NAME : "${LAMBDA_FUNCTION_NAME}"
    LAMBDA_ALIAS_NAME : "${LAMBDA_ALIAS_NAME}"
phases:
  install:
    runtime-versions:
      nodejs: $NODE_RUNTIME
    commands:
      - echo "Entered the install phase..."

      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure Node is installed"
      - echo `node --version`
      - echo "Making sure GIT cli is installed"
      - echo `git --version`
      - echo "Making sure JFROG cli is installed"
      - echo `jf --version`
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo present working directory `pwd`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
        fi
      - pwd
      - ls -l

      #jfrog authentication
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - jf rt ping
      - jf c s

      # Jfrog repo configuraiton
      - jf npmc --repo-deploy $ARTIFACTORY_REPO_KEY --repo-resolve $ARTIFACTORY_REPO_KEY

      # remove dev dependencies
      - rm -rf node_modules
      - rm package-lock.json
      - jf npm install --omit=dev
      - ls -l node_modules/

      # - | 
      #   if [[ "${LAMBDA_UPDATE}" = "true" ]] ; then
      #     ARTIFACT_ID=$LAMBDA_FUNCTION_NAME
      #     VERSION=$(aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME | jq -r .Version)
      #   else
      #     # getting project name and version from package.json
      #     VERSION=$(cat package.json | jq -r .version)
      #     ARTIFACT_ID=$(cat package.json | jq -r .name)
      #   fi
   
      - ARTIFACT_VERSION=$(cat package.json | jq -r .version)
      - ARTIFACT_ID=$(cat package.json | jq -r .name)
      - ARTIFACT_FULL_NAME=$ARTIFACT_ID-$ARTIFACT_VERSION.zip
      # making zip file
      - echo "Zipping deployment package with Artifact name as $ARTIFACT_FULL_NAME."
      - zip -r $ARTIFACT_FULL_NAME *
      
      # #generating path to deploy artifact into artifactory
      - ARTIFACTORY_REPO_KEY_PATH=$ARTIFACTORY_REPO_KEY/$ARTIFACT_ID/$ARTIFACT_VERSION/
      
      # - echo " *** Printing Variables *** "
      - export SERVER_ID="$ARTIFACTORY_HOST"
      - export CODEBUILD_NAME=`echo "$CODEBUILD_BUILD_ID" | awk '{split($0,a,":"); print a[1]}'`

      - echo "CODEBUILD_BUILD_ID - $CODEBUILD_BUILD_ID"
      - echo "CODEBUILD_NAME - $CODEBUILD_NAME"
      - echo "CODEBUILD_BUILD_NUMBER - $CODEBUILD_BUILD_NUMBER"

      - echo "SERVER_ID - $SERVER_ID"
      - echo "ARTIFACTORY_REPO_KEY_PATH - $ARTIFACTORY_REPO_KEY_PATH"
      - echo "ARTIFACTORY_REPO_KEY - $ARTIFACTORY_REPO_KEY"
      - echo "ARTIFACT_FULL_NAME - $ARTIFACT_FULL_NAME"
      - echo "ARTIFACTORY_AUTH_PREFIX - $ARTIFACTORY_AUTH_PREFIX"

      # # Uploading Artifact
      - jf rt u "$ARTIFACT_FULL_NAME" $ARTIFACTORY_REPO_KEY_PATH --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST/artifactory" --build-name="$CODEBUILD_NAME" --build-number="$CODEBUILD_BUILD_NUMBER"
     
      # Collecting environment variables
      - jf rt bce "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER"

      # # Publishing dependencies
      - |
        if [ "$DEPENDENCY_FILES_LOCATION" != "" ] ; then
            jf rt bad "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" "$DEPENDENCY_FILES_LOCATION"
        fi
      # # Publishing build-info
      - jf rt bp "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" --build-url="$CODEBUILD_BUILD_ARN"
      - jf rt bpr "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" $ARTIFACTORY_REPO_KEY --status="released"

      - jf c rm $SERVER_ID --quiet
      - jf c s
 
      # updating the Lambda function
      - | 
        if [[ "${LAMBDA_UPDATE}" = "true" ]] ; then
          echo "***Updating lambda Function $LAMBDA_FUNCTION_NAME***"
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$ARTIFACT_FULL_NAME
          sleep 10
          LAMBDA_VERSION=$(aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME | jq -r .Version)
          aws lambda update-alias --function-name $LAMBDA_FUNCTION_NAME --name $LAMBDA_ALIAS_NAME --function-version $LAMBDA_VERSION
          echo "LAMBDA UPDATE AND PUBLISH NEW VERSION DONE!!"
        else
          echo "Recieved LAMBDA_UPDATE as false, skipping lambda function update"
        fi

artifacts:
    files:
      - '**/*'

#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.npm/**/*'