# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      java: $JAVA_RUNTIME
    commands:
      - echo listing files and directories
      - ls -lart
      - yum install -y make
      - make --version
      - git --version
      # git secrets installation support for git version >=2.37, more details: https://github.com/awslabs/git-secrets/issues/220
      - |
        [[ $(git --version) >=2.37 ]] && ln -s "$(which echo)" /usr/local/bin/say
      - echo "Installing the git secrets using makefile"
      - git init
      - make install
      - pwd
      - Test=`pwd`

  pre_build:
    commands:
      - 'ls -lart'
      #- cat $CODEBUILD_SRC_DIR_secrets-code/patterns.txt
      - echo "Scanning for the secrets for application repo"
      - cd $CODEBUILD_SRC_DIR_code
      - ls -larth
      - git init
      - git status
      - git secrets --install
      - git secrets --register-aws
      - sh $Test/regex.sh
      - git secrets --list
      - git secrets --scan --untracked

  build:
    commands:
      - ls -larth
      - echo "Secrets Scanning completed"
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
      - '**/*'


#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.m2/**/*'