output "application_id" {
  description = "The Application ID generated by AWS"
  value       = module.appconfig.id
}

output "application_arn" {
  description = "The Application ARN generated by AWS"
  value       = module.appconfig.arn
}

output "application_tags" {
  description = "A map of all tags associated withe the resource."
  value       = module.appconfig.tags
}
