variable "bucket_name" {
  description = "Name of the S3 bucket. Conflicts with bucket_prefix"
  type        = string
  validation {
    condition     = length(var.bucket_name) == 0 || length(regexall("^[a-z0-9][a-z0-9\\-.]{1,61}[a-z0-9]$", var.bucket_name)) > 0
    error_message = "Input variable bucket_name is invalid. Please refer to https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html."
  }
}

variable "kms_key_arn" {
  description = "KMS key arn for S3 bucket encryption. By default it would be set to null"
  type        = string
  default     = null
  validation {
    condition     = (var.kms_key_arn == null || can(regex("^arn:aws:kms:\\w+(?:-\\w+)+:[[:digit:]]{12}:key/([a-zA-Z0-9])+(.*)$", var.kms_key_arn)))
    error_message = "Please enter valid kms_key_arn parameter."
  }
}


variable "force_destroy" {
  type        = bool
  default     = false
  description = "A boolean string that indicates all objects should be deleted from the bucket so that the bucket can be destroyed without error. These objects are not recoverable"
}

variable "tags" {
  description = "A map of tags to add to all resources."
  type        = map(string)
}

# validate the tags passed
module "validate_tags" {
  source  = "app.terraform.io/pgetech/validate-pge-tags/aws"
  version = "0.1.2"
  tags    = var.tags
}

variable "acl" {
  type        = string
  default     = "private"
  description = "The [canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl) to apply. We recommend `private` to avoid exposing sensitive information. Conflicts with `grants`."
}
variable "versioning" {
  type        = string
  default     = "Disabled"
  description = "Provides a resource for controlling versioning on an S3 bucket. Deleting this resource will either suspend versioning on the associated S3 bucket or simply remove the resource from Terraform state if the associated S3 bucket is unversioned."
}
variable "grants" {
  type = list(object({
    id          = string
    type        = string
    permissions = list(string)
    uri         = string
  }))
  default     = null
  description = "An ACL policy grant. Conflicts with `acl`. Set `acl` to `null` to use this."
}

variable "policy" {
  type        = string
  default     = "{}"
  description = "A valid policy JSON document. This is a JSON formatted string. For more information about building AWS IAM policy documents with Terraform, see the AWS IAM Policy Document Guide. Statement having SIDs that match policy SIDs generated by this module template will override them."
  validation {
    condition     = can(jsondecode(var.policy))
    error_message = "Must be valid JSON for CMK policy."
  }
}

variable "block_public_acls" {
  type        = bool
  description = "Please get the cyber approval before setting it to false. PG&E recommded value is true. It triggers Prisma alerts on false setting. This is a setting that Whether Amazon S3 should block public ACLs for this bucket."
  default     = true
}

variable "block_public_policy" {
  type        = bool
  description = "Please get the cyber approval before setting it to false. PG&E recommded value is true. It triggers Prisma alerts on false setting. This is a setting that Whether Amazon S3 should block public bucket policies for this bucket."
  default     = true
}

variable "ignore_public_acls" {
  type        = bool
  description = "Please get the cyber approval before setting it to false. PG&E recommded value is true. It triggers Prisma alerts on false setting. This is a setting that Whether Amazon S3 should ignore public ACLs for this bucket."
  default     = true
}

variable "restrict_public_buckets" {
  type        = bool
  description = "Please get the cyber approval before setting it to false. PG&E recommded value is true. It triggers Prisma alerts on false setting. This is a setting that Whether Amazon S3 should restrict public bucket policies for this bucket."
  default     = true
}

variable "target_bucket" {
  type        = string
  description = "The name of the bucket where you want Amazon S3 to store server access logs."
  default     = null
}

variable "target_prefix" {
  type        = string
  description = "A prefix for all log object keys."
  default     = null
}

variable "expected_bucket_owner" {
  description = "The account ID of the expected bucket owner"
  type        = string
  default     = null
}

variable "request_payer" {
  description = "(Optional) Specifies who should bear the cost of Amazon S3 data transfer. Can be either BucketOwner or Requester. By default, the owner of the S3 bucket would incur the costs of any data transfer. See Requester Pays Buckets developer guide for more information."
  type        = string
  default     = null
}

variable "object_lock_configuration" {
  type = object({
    mode  = string #Valid values are GOVERNANCE and COMPLIANCE.
    days  = number
    years = number
  })
  default     = null
  description = "With S3 Object Lock, you can store objects using a write-once-read-many (WORM) model. Object Lock can help prevent objects from being deleted or overwritten for a fixed amount of time or indefinitely."

}

variable "owner" {
  description = "The owner configuration block for grants in s3 acl. Conflicts with 'acl'"
  type        = map(string)
  default     = {}
}

variable "cors_rule_inputs" {
  type = list(object({
    allowed_headers = list(string)
    allowed_methods = list(string)
    allowed_origins = list(string)
    expose_headers  = list(string)
    max_age_seconds = number
    id              = string
  }))
  default     = null
  description = "Specifies the allowed headers, methods, origins,id and exposed headers when using CORS on this bucket"
}

variable "intelligent_tiering_name" {
  description = "intelligent tiering name"
  type        = string
  default     = "default-name"
}
variable "deeparchive_days" {
  description = "No of consecutive daysof no access deep archive"
  type        = number
  default     = 180
}
variable "archive_days" {
  description = "No of consecutive daysof no access archive"
  type        = number
  default     = 90
}