apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: cmk-nodeclass
spec:
  role: "noderole-20260218212639247100000001"
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        Name: "eks-cluster-sg-e6bo-auto-test-1048337249"
  ephemeralStorage:
    size: "160Gi"
    kmsKeyID: "arn:aws:kms:us-west-2:514712703977:key/2b90abff-f8b9-4dcc-a984-53389b48dcd4"