jobs:
- job: DeployInfraJob
  displayName: "Deploy Infrastructure"
  pool:
    vmImage: ubuntu-latest
    
  workspace:
    clean: all

  #############################################################################
  # Steps
  #############################################################################
  steps:

    ###########################################################################
    # Download App Artifact
    ###########################################################################
    - task: DownloadPipelineArtifact@2
      displayName: "Download infrastructure code"
      inputs:
        artifactName: epic-app
        targetPath: $(System.DefaultWorkingDirectory)/${{ parameters.appName }}


    ###########################################################################
    # Deploy Infrastructure with Terraform
    ###########################################################################
    - task: AWSShellScript@1
      displayName: 'Terraform Init'
      inputs:
        awsCredentials: 'AWS'
        regionName: ${{ parameters.awsRegion }}
        scriptType: 'inline'
        inlineScript: |
          cd ${{ parameters.appName }}/.infra

          terraform init \
            -backend-config="bucket=pge-epic-terraform-state-${{ parameters.environment }}" \
            -backend-config="dynamodb_table=pge-epic-${{ parameters.environment }}" \
            -backend-config="key=${{ parameters.repoName }}/${{ parameters.environment }}/terraform.tfstate" \
            -backend-config="region=${{ parameters.awsRegion }}" \
            -backend-config="encrypt=true"

    - task: AWSShellScript@1
      displayName: 'Terraform Validate'
      inputs:
        awsCredentials: 'AWS'
        regionName: ${{ parameters.awsRegion }}
        scriptType: 'inline'
        inlineScript: |
          cd ${{ parameters.appName }}/.infra

          terraform validate

    - task: AWSShellScript@1
      displayName: 'Terraform Plan'
      condition: eq('${{ parameters.terraformAction }}', 'apply')
      inputs:
        awsCredentials: 'AWS'
        regionName: ${{ parameters.awsRegion }}
        scriptType: 'inline'
        inlineScript: |
          cd ${{ parameters.appName }}/.infra

          terraform plan \
            -var="aws_account_id=${{ parameters.awsAccountId }}" \
            -var="environment=${{ parameters.environment }}" \
            -var="aws_region=${{ parameters.awsRegion }}" \
            -out=tfplan

    # - task: AWSShellScript@1
    #   displayName: 'Terraform Apply'
    #   condition: eq('${{ parameters.terraformAction }}', 'apply')
    #   inputs:
    #     awsCredentials: 'AWS'
    #     regionName: ${{ parameters.awsRegion }}
    #     scriptType: 'inline'
    #     inlineScript: |
    #       cd ${{ parameters.appName }}/.infra

    #       terraform apply -auto-approve tfplan

    # - task: AWSShellScript@1
    #   displayName: 'Terraform Plan Destroy'
    #   condition: eq('${{ parameters.terraformAction }}', 'destroy')
    #   inputs:
    #     awsCredentials: 'AWS'
    #     regionName: ${{ parameters.awsRegion }}
    #     scriptType: 'inline'
    #     inlineScript: |
    #       cd ${{ parameters.appName }}/.infra

    #       terraform plan -destroy \
    #         -var="aws_account_id=${{ parameters.awsAccountId }}" \
    #         -var="environment=${{ parameters.environment }}" \
    #         -var="aws_region=${{ parameters.awsRegion }}" \
    #         -out=tfplan-destroy

    # - task: AWSShellScript@1
    #   displayName: 'Terraform Destroy'
    #   condition: eq('${{ parameters.terraformAction }}', 'destroy')
    #   inputs:
    #     awsCredentials: 'AWS'
    #     regionName: ${{ parameters.awsRegion }}
    #     scriptType: 'inline'
    #     inlineScript: |
    #       cd ${{ parameters.appName }}/.infra

    #       terraform apply -auto-approve tfplan-destroy
