# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACT_NAME
    - PROJECT_ROOT_DIRECTORY
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY    
    - PROJECT_FILE_LOCATION
    - DOTNET_VERSION
  variables:
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    S3_BINARIES_STORE : "${S3_BINARIES_STORE}"
phases:
  install:
   runtime-versions:
     dotnet: $DOTNET_VERSION
   commands:
     - echo "Entered the install phase..."
    #  - yum install -y mono-devel
     
      #Download the latest stable `nuget.exe` to `/usr/local/bin`
    #  - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe     
    #  - mv nuget.exe /usr/local/bin
     
    #  # Deleting the default dotnet version 
    #  - |
    #     if [ -d "/root/.dotnet" ]; then
    #       sudo rm -rf /root/.dotnet
    #     fi
        
    #  # Install dotnet CLI with the provided version    
    #  - rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
    #  - yum install -y dotnet-runtime-$DOTNET_VERSION
    #  - yum install -y dotnet-sdk-$DOTNET_VERSION

  pre_build:
    commands:
      - echo Restore started on `date`
      # - export DOTNET_ROOT=/usr/share/dotnet
      # - export MSBuildSDKsPath=$DOTNET_ROOT/sdk/$($DOTNET_ROOT/dotnet --version)/Sdks
      # - export PATH="$PATH:$DOTNET_ROOT"
      # - export PATH="$PATH:$HOME/.dotnet/tools"
      
      - echo "Making sure dotnet is installed"
      - echo `dotnet --version`
      - dotnet --list-sdks
      - dotnet --list-runtimes
      
      # Setting up Jfrog as the source artifactory
      # - mono /usr/local/bin/nuget.exe sources Add -Name Artifactory -Source $ARTIFACTORY_HOST/artifactory/api/nuget/$ARTIFACTORY_REPO_KEY -username $ARTIFACTORY_USER -password $ARTIFACTORY_TOKEN
      # - mono /usr/local/bin/nuget.exe setapikey $ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -Source Artifactory

      # #- dotnet restore $PROJECT_ROOT_DIRECTORY/$PROJECT_MSBUILD_FILE_LOCATION
      # - mono /usr/local/bin/nuget.exe restore $PROJECT_ROOT_DIRECTORY -Source Artifactory
     # - mono /usr/local/bin/nuget.exe install bootstrap -Source Artifactory # Testing an installtion to be cached in jfrog
      
  build:
    commands:
      - echo Build started on `date`
      - echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - pwd
      - ls -lrta
      
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - pwd
      - ls -lrta
      - echo "$PROJECT_FILE_LOCATION"

      #Downloads and installs a package into a project, defaulting to the current folder, using jfrog artifactory as package sources
      - dotnet restore .
      
      #Publishing the application and its dependencies to a folder
      - dotnet publish -c release -r linux-x64 -o ./build_artifacts .
      
      - ls -lrt
      - ls -lrta ./build_artifacts
      # - zip $ARTIFACT_NAME ./build_artifacts/*
      # - find . -type f -name "$ARTIFACT_NAME" -exec cp {} ./build_artifacts \;
      # - ls -lart
      # - ls -lrta ./build_artifacts

      # Checking IsPackable attribute in csproj file. If the value is true, the 'dotnet pack' command to create a .nupkg file.
      # - ISPACKABLE=$(cat $PROJECT_FILE_LOCATION/*.csproj | grep "IsPackable" | head -1 | cut -d '>' -f2 | cut -d '<' -f1)
      # - echo Is the dotnet Project packable "$ISPACKABLE"
      
      # - |
      #    if [ "$ISPACKABLE" = 'true' ]; then
      #      dotnet pack -c release -o ./build_artifacts
      #    else
      #      mkdir build_artifacts
      #      pwd && ls -lrt && ls -lrt $PROJECT_FILE_LOCATION
      #      dotnet restore .
      #      # dotnet publish -c release -r linux-x64 -o ./build_artifacts WebApplicationSample/WebApplicationSample.csproj 
      #      ls -lrt ./build_artifacts      
      #      zip $ARTIFACT_NAME ./build_artifacts/*
      #      ls -lrt
      #      find . -type f -name "$ARTIFACT_NAME" -exec cp {} ./build_artifacts \;
      #      ls -lrt
      #    fi
      # - ls -lrt ./build_artifacts
      # - ls -lrta $CODEBUILD_SRC_DIR

artifacts:
  files:
   - ./**/*
#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.nuget/**/*'
  