version: 0.2
env:
 

  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      java: $JAVA_RUNTIME
    commands:
      - echo "Entered the install phase..."
      
      - echo " Install Json parser jq for JSON parser"
      - yum install jq

      - echo "Installing Twistcli curl -u $TWISTLOCK_USER_ID:$TWISTLOCK_USER_TOKEN -o twistcli $TWISTLOCK_CONSOLE/api/v1/util/twistcli"
      - curl -u $TWISTLOCK_USER_ID:$TWISTLOCK_USER_TOKEN -o twistcli $TWISTLOCK_CONSOLE/api/v1/util/twistcli
      - chmod +x ./twistcli
      - export PATH=$PWD/:$PATH
      - ./twistcli --version
      - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_TOKEN $ARTIFACTORY_DOCKER_REGISTRY

      - echo "install Helm CLI for building Helm charts"
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version
      

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure Java is installed"
       
    

  build:
    on-failure: ABORT
    commands:
      - echo "Entered the Twistlock scanning phase execution..."
     
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi   
      
      - echo "Update Docker file with twistlock defenders for EKS fargate work loads only"
      - |
         if [[ "$IS_EKS_FARGATE" == true  ]]; then
            ./twistcli app-embedded embed -u $TWISTLOCK_USER_ID -p $TWISTLOCK_USER_TOKEN  --address $TWISTLOCK_CONSOLE --app-id $CONTAINER_NAME-$APP_ID --console-host $TWISTLOCK_CONSOLE_HOST --data-folder "/tmp" --output-file app-embeded-archive-file Dockerfile
            rm -rf Dockerfile
            unzip app-embeded-archive-file
         fi
      - echo "Entered the Twistlock scanning phase execution..."
    
      - ls -al

      - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - IMAGE_TAG=pge-${VERSION}
      - CHART_VERSION=${VERSION}
      - IMAGE_TYPE="pge-app"
      - docker build . -t $CONTAINER_NAME:$IMAGE_TAG --build-arg BASE_IMAGE_URL=$ARTIFACTORY_DOCKER_REGISTRY --build-arg ENVIRONMENT=$APP_ENVIRONMENT --build-arg OWNER=$APP_OWNERS --build-arg IMAGE_TYPE=$IMAGE_TYPE
      
       # Scan using Twistlock
      - echo Twistlock scanning ....
      - ./twistcli images scan -u $TWISTLOCK_USER_ID -p $TWISTLOCK_USER_TOKEN --details --address $TWISTLOCK_CONSOLE --output-file twistlock_scan_results.json $CONTAINER_NAME:$IMAGE_TAG    

      - |
         if [[ "$PUBLISH_DOCKER_REGISTRY" == "ECR" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            docker tag $CONTAINER_NAME:$IMAGE_TAG $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:$IMAGE_TAG
            docker tag $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:$IMAGE_TAG $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:pge-latest
         fi

         if [[ "$PUBLISH_DOCKER_REGISTRY" == "JFROG" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            docker tag $CONTAINER_NAME:$IMAGE_TAG $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:$IMAGE_TAG
            docker tag $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:$IMAGE_TAG $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:pge-latest
         fi

  

      
  post_build:
    commands:
       - echo "Twistlock scanning..."
       - echo $PUBLISH_DOCKER_REGISTRY
       - echo $CODEDEPLOY_PROVIDER
       - |
          echo 'Build is successfully completed'
          if [[ "$PUBLISH_DOCKER_REGISTRY" == "ECR" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            echo 'Push docker images to Elastic Container Registry'
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com
            aws ecr create-repository --repository-name $CONTAINER_NAME || true
            docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:$IMAGE_TAG
            docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:pge-latest
          fi

          if [[ "$PUBLISH_DOCKER_REGISTRY" == "JFROG" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            echo 'Push docker images to Jfrog Docker registry'
            docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_TOKEN $ARTIFACTORY_DOCKER_REGISTRY
            docker push $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:$IMAGE_TAG
            docker push $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:pge-latest
          fi

          if [[ "$PUBLISH_DOCKER_REGISTRY" == "JFROG" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            DEPLOY_IMAGE=$ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:pge-latest
          else
            DEPLOY_IMAGE=$AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:pge-latest
          fi
          
          echo " update image tag, generate helm packages and upload it to artifactory"
          cd helm-chart/chart
          sed -i -e 's|<DOMAIN>|'"$CUSTOM_DOMAIN_NAME"'|g' -e 's|<CERTIFICATES>|'"$ACM_SSL_ARN"'|g' values.yaml
          
          ls -al 
          python ../values_updater.py $IMAGE_TAG values.yaml
          helm package .  --version $CHART_VERSION
          curl -u$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -T $CONTAINER_NAME-$CHART_VERSION.tgz "$ARTIFACTORY_HOST/artifactory/$HELMCHART_LOCAL_REPO/$CONTAINER_NAME-$CHART_VERSION.tgz" 


#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.m2/**/*'
