#
# Filename    : modules/utils/modules/workspace-info/outputs.tf
# Date        : 19 Apr 2023
# Author      : Balaji Venkataraman (b1v6@pge.com)
# Description : get workspace name and id if executed in terraform cloud;
#               when executed locally, get pwd and user details
#

output "name" {
  description = "workspace name or working directory"
  value       = local.ws_name
}

output "id" {
  description = "workspace id or user id"
  value       = local.ws_id
}

output "all" {
  description = "map of the output generated by data external"
  value       = local.ws_all
}
