version: 0.2

phases:
  install:
    commands:
      - echo "Download SonarScanner CLI"
      - wget -q -O sonar-scanner-cli.zip $SONAR_CLI_DOWNLOAD_URL
      - echo "Unzip"
      - unzip sonar-scanner-cli.zip
      - rm sonar-scanner-cli.zip
      - SONAR_DIR_NAME=$(find . -maxdepth 1 -type d -name "sonar-scanner*" | head -n 1)
      - ls -la ./$SONAR_DIR_NAME/bin/
      - export PATH=$PATH:$(pwd)/$SONAR_DIR_NAME/bin/
      - sonar-scanner -v
      - echo "Sonar Scanner is installed"
  build:
    commands:
      - cd lambdas/${lambda_name}
      - npm install
      - npm test

      - echo $PATH
      - sonar-scanner -Dsonar.token="$SONAR_TOKEN" || exit 0

  post_build:
    commands:
      - echo SonarQube Scanner completed on `date`
