# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables: #export environment variables from the current build stage to subsequent stages in the pipeline
    - PROJECT_ROOT_DIRECTORY
    - PYTHON_RUNTIME
    - AWS_ORG_ID
phases:
  install:
    runtime-versions:
      python: $PYTHON_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - echo "installing python dependencies"
      - pip install -r "${PROJECT_ROOT_DIRECTORY}/requirements.txt"
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.51.7/terragrunt_linux_amd64
      - mv terragrunt_linux_amd64 terragrunt
      - chmod 755 terragrunt
      - sudo mv terragrunt /codebuild/user/bin/terragrunt
    finally:
      - export
      - find . -print
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure Python is installed"
      - echo "python version is `python --version`" && echo "pip version is `pip --version`"
      - echo "Making sure terraform is installed"
      - terraform --version
      # Create .terraformrc with token
      - mkdir -p ~/.terraform.d
      - sed "s/REPLACEME/$TF_TOKEN/" "${PROJECT_ROOT_DIRECTORY}/credentials.tfrc.json" > ~/.terraform.d/credentials.tfrc.json
      - cat ~/.terraform.d/credentials.tfrc.json
      - terragrunt --version

  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase execution..."
      - echo Build started on `date`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - ls -al
      - git clone "https://cheekuru2023:$CCOE_GITHUB_PAT@github.com/pgetech/ccoe-ssm-autopatch-mgt.git"
      - cd ccoe-ssm-autopatch-mgt/gen-tfc
      - ls -al 
      - git status
      - python gen_ou_struct.py "${AWS_ORG_ID}"  # This generates file, org-unit-id.hcl
      - terragrunt init
      - git config --global user.name "ccoe user"
      - git config --global user.email "sycz@pge.com"
      - are_there_changes=$(git status) 
      - echo $are_there_changes
      - |        
      
        if [[ $are_there_changes == *"nothing to commit"* ]]; then
          echo "There are no changes to commit" 
          
        else 
          echo "There are new changes to the repo" 
          git add -A
          git status
          git commit -m "Regenerating Terraform Code"
          git push 
        fi
      

artifacts:
    files:
      - '**/*'

