output "application_id" {
  description = "The AppConfig application ID"
  value       = module.application.id
}

output "application_arn" {
  description = "The AppConfig application ARN"
  value       = module.application.arn
}

output "application_tags" {
  description = "All tags associated with the application."
  value       = module.application.tags
}

output "environment_arn" {
  description = "ARN of the AppConfig Environment."
  value       = module.environment.arn
}

output "environment_state" {
  description = "State of the environment."
  value       = module.environment.state
}

output "environment_tags" {
  description = "A map of all tags assigned to the environment."
  value       = module.environment.tags
}

output "environment_id" {
  description = "The AppConfig environment ID"
  value       = module.environment.id
}

output "configuration_profile_id" {
  description = "The AppConfig configuration profile ID"
  value       = module.configuration_profile.id
}

output "configuration_profile_arn" {
  description = "The ARN generated by AWS"
  value       = module.configuration_profile.arn
}

output "configuration_profile_tags" {
  description = "A map of all tags associated with the resource."
  value       = module.configuration_profile.tags
}

output "hosted_configuration_id" {
  description = "The Configuration Profile ID generated by AWS"
  value       = module.hosted_configuration_version.id
}

output "hosted_configuration_arn" {
  description = "The ARN generated by AWS"
  value       = module.hosted_configuration_version.arn
}

output "hosted_configuration_version" {
  description = "Version number of the hosted configuration."
  value       = module.hosted_configuration_version.version
}

