version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - IMAGE_TAG
    - DEPLOY_IMAGE
phases:
  install:
    runtime-versions:
      java: $JAVA_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - echo "Installing WIZ CLI"
      - echo $APP_ENVIRONMENT
      - curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
      - export PATH=$PWD/:$PATH
      - wizcli version
      - wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
      - echo "$ARTIFACTORY_TOKEN" | docker login --username "$ARTIFACTORY_USER" --password-stdin "$ARTIFACTORY_DOCKER_REGISTRY"
      
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo `jf --version`

  build:
    on-failure: ABORT
    commands:
      - echo "Entered the Wiz scanning phase execution..."
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - ls -al
      # Image Tagging with pge-<build-id>
      - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - IMAGE_TAG=pge-${VERSION}
      - docker build . -t $CONTAINER_NAME:$IMAGE_TAG --build-arg BASE_IMAGE_URL=$ARTIFACTORY_DOCKER_REGISTRY --build-arg ENVIRONMENT=$APP_ENVIRONMENT --build-arg OWNER=$APP_OWNERS --build-arg IMAGE_TYPE=$IMAGE_TYPE
      - |
         if [[ "$PUBLISH_DOCKER_REGISTRY" == "ECR" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            docker tag $CONTAINER_NAME:$IMAGE_TAG $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:$IMAGE_TAG
            docker tag $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:$IMAGE_TAG $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:pge-latest
         fi
         if [[ "$PUBLISH_DOCKER_REGISTRY" == "JFROG" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            docker tag $CONTAINER_NAME:$IMAGE_TAG $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:$IMAGE_TAG
            docker tag $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:$IMAGE_TAG $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:pge-latest
         fi
      - |
          if [[ "$PUBLISH_DOCKER_REGISTRY" == "JFROG" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            DEPLOY_IMAGE=$ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:pge-latest
          else
            DEPLOY_IMAGE=$AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:pge-latest
          fi
      
      # Scan using Wiz
      - echo wiz scanning ....
      - echo scanning image $CONTAINER_NAME:$IMAGE_TAG
      - docker images 
      - wizcli docker scan --image $CONTAINER_NAME:$IMAGE_TAG -f json > $CONTAINER_NAME:$IMAGE_TAG.json
      - ls -ltra
      - chmod +x $CONTAINER_NAME:$IMAGE_TAG.json
      - REPORT_FILE=$CONTAINER_NAME:$IMAGE_TAG.json
      - echo $APP_ENVIRONMENT
      - SCAN_STATUS=$(jq -r ".status.\"verdict\"" $REPORT_FILE)
      - echo "Analyzing WIZ Scan result"
      - |
        if [ "$SCAN_STATUS" == 'PASSED_BY_POLICY' ]; then
          echo "SCANNING PASSED Proceeding further"
        else
          REPORT_URL=$(jq -r '.reportUrl' $CONTAINER_NAME:$IMAGE_TAG.json)
          echo "Found Vulnerabilities or Compliance Issues. SEVERITY - "
          echo "For more details access the report here $REPORT_URL"
          echo "***** Found vulnerabilities and not pushing the image - *****"
          if [[ "${APP_ENVIRONMENT,,}" != "dev" ]]; then 
              exit 1;
          else 
             echo "###################################################################################################################"
             echo ******* CONTINUING as its "${APP_ENVIRONMENT,,}" ENVIRONMENT and please fix vulnerabilities before QA/PROD ******
             echo "###################################################################################################################"
          fi
        fi

  post_build:
    commands:
      - echo "Entering Publishing phase..."
      - echo $PUBLISH_DOCKER_REGISTRY
      - echo $LAMBDA_UPDATE
      - |
          echo 'Build is successfully completed'
          if [[ "$PUBLISH_DOCKER_REGISTRY" == "ECR" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            echo 'Push docker images to Elastic Container Registry'
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com
            aws ecr describe-repositories --repository-names $CONTAINER_NAME || aws ecr create-repository --repository-name $CONTAINER_NAME 
            docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:$IMAGE_TAG
            docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CONTAINER_NAME:pge-latest
          fi
          
          if [[ "$PUBLISH_DOCKER_REGISTRY" == "JFROG" || "$PUBLISH_DOCKER_REGISTRY" == "BOTH" ]]; then
            echo 'Push docker images to Jfrog Docker registry'
              echo "$ARTIFACTORY_TOKEN" | docker login --username "$ARTIFACTORY_USER" --password-stdin "$ARTIFACTORY_DOCKER_REGISTRY"
            docker push $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:$IMAGE_TAG
            docker push $ARTIFACTORY_DOCKER_REGISTRY/$CONTAINER_NAME:pge-latest
          fi
      - echo "Lambda update"
      - |
        set -e
        if [[ "${LAMBDA_UPDATE}" = "true" && "${LAMBDA_FUNCTION_NAME}" != "" ]] ; then

          echo "***Updating lambda Function $LAMBDA_FUNCTION_NAME*** with image $DEPLOY_IMAGE***"
          aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --image-uri "$DEPLOY_IMAGE" --region "$AWS_REGION"
          aws lambda wait function-updated --function-name "$LAMBDA_FUNCTION_NAME" --region "$AWS_REGION"
          LAMBDA_VERSION=$(aws lambda publish-version --function-name "$LAMBDA_FUNCTION_NAME" --region "$AWS_REGION" | jq -r .Version)
          if [[ "${LAMBDA_ALIAS_NAME}" != "" ]]; then
            aws lambda update-alias --function-name "$LAMBDA_FUNCTION_NAME" --name "$LAMBDA_ALIAS_NAME" --function-version "$LAMBDA_VERSION" --region "$AWS_REGION"
          fi
          echo "LAMBDA UPDATE AND PUBLISH NEW VERSION DONE!!"
          
        elif [[ "${LAMBDA_UPDATE}" = "false" ]] ; then
          echo "Recieved LAMBDA_UPDATE as false, skipping lambda function update"
        else
          echo "Not a Lambda function, skipping the update"
        fi

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.m2/**/*'