# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - DEPENDENCY_FILES_LOCATION
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH   : "${GIT_REPO_BRANCH}"
phases:
  install:
    runtime-versions:
      java: $JAVA_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - yum install -y git
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure Java is installed"
      - echo `java -version`
      - echo "Making sure Maven is installed"
      - echo `mvn --version`
      - echo "CCOE-3824 - Making sure GIT cli is installed"
      - echo `git --version`
      - echo "Making sure JFROG cli is installed"
      - echo `jf --version`
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase execution..."
      - echo Build started on `date`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - ls -lrt target/
      - echo "Deploy maven package to Artifactory Host"
      - export COMMAND=$(echo "mvn deploy -DskipTests -Dinternal_user=$ARTIFACTORY_USER -Dinternal_pw=$ARTIFACTORY_TOKEN ${OPTIONAL_ATTRIBUTES} -s settings.xml")
      - echo $COMMAND
      - eval $COMMAND

      - export SERVER_ID="$ARTIFACTORY_HOST"
      - export CODEBUILD_NAME=`echo "$CODEBUILD_BUILD_ID" | awk '{split($0,a,":"); print a[1]}'`

      - echo "CODEBUILD_BUILD_ID - $CODEBUILD_BUILD_ID"
      - echo "CODEBUILD_NAME - $CODEBUILD_NAME"
      - echo "CODEBUILD_BUILD_NUMBER - $CODEBUILD_BUILD_NUMBER"
      - echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - echo "GIT_REPO_BRANCH - $GIT_REPO_BRANCH"
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION - $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "SERVER_ID - $SERVER_ID"

      - echo "ARTIFACTORY_REPO_KEY - $ARTIFACTORY_REPO_KEY"
      - echo "ARTIFACTORY_AUTH_PREFIX - $ARTIFACTORY_AUTH_PREFIX"
      - echo "ARTIFACTORY_USER - $ARTIFACTORY_USER"

      - jf c add "$SERVER_ID" --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST" --interactive=false
      - jf c s
      - jf rt ping

      - jf rt bce "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER"

      - |
        if [ ! -f "version.toml" ] ; then
          echo "***version.toml does not exist, skipping setting properties, if you wish to download artifact from artifactory in QA or prod and skip build and scan stages, please provide version.toml file in root directory***"
          echo ""
          if [ "$LAMBDA_UPDATE" = "true" ] ; then
            echo "*** Getting Artifact name from pom.xml using Artifact ID and Version for lambda update with latest artifact***"
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -Dinternal_user=$ARTIFACTORY_USER -Dinternal_pw=$ARTIFACTORY_TOKEN ${OPTIONAL_ATTRIBUTES} -s settings.xml)
            ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout -Dinternal_user=$ARTIFACTORY_USER -Dinternal_pw=$ARTIFACTORY_TOKEN ${OPTIONAL_ATTRIBUTES} -s settings.xml)
            ARTIFACT_TYPE=$(mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout -Dinternal_user=$ARTIFACTORY_USER -Dinternal_pw=$ARTIFACTORY_TOKEN ${OPTIONAL_ATTRIBUTES} -s settings.xml)
            ARTIFACT_NAME=$ARTIFACT_ID-$VERSION.$ARTIFACT_TYPE
            echo "Artifact name is $ARTIFACT_NAME"
          fi
        else
          echo "**** version.toml exists, getting values of group_id and artifact_id from version.toml ****"
          ARTIFACT_GROUPID=$(cat version.toml | grep group_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          VERSION=$(cat version.toml | grep version | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_ID=$(cat version.toml | grep artifact_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_NAME=$(cat version.toml | grep artifact_name | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_PATH=$ARTIFACT_GROUPID/$ARTIFACT_ID/$VERSION
   
          echo "setting properties with branch name as ${GIT_REPO_BRANCH} on artifact"  
          jf rt sp "$ARTIFACTORY_REPO_KEY/$ARTIFACT_PATH/$ARTIFACT_NAME" "branch=${GIT_REPO_BRANCH}"
        fi
      # Publishing dependencies
      - |
        if [ "$DEPENDENCY_FILES_LOCATION" != "" ] ; then
            jf rt bad "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" "$DEPENDENCY_FILES_LOCATION"
        fi
      # Publishing build-info
      - jf rt bp "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" --build-url="$CODEBUILD_BUILD_ARN"
      - jf rt bpr "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" $ARTIFACTORY_REPO_KEY --status="released"
      - jf c rm $SERVER_ID --quiet
      - jf c s

      # updating the Lambda function
      - |
        set -e
        if [[ "${LAMBDA_UPDATE}" = "true" && "${LAMBDA_FUNCTION_NAME}" != "" ]] ; then

          [ ! -f "target/${ARTIFACT_NAME}" ] && echo "${ARTIFACT_NAME} does not exist in the target directory, make sure to generate jar file with Artiafct ID and version in target directory" || echo "${ARTIFACT_NAME} exists in the target directory, proceeding with lambda update using this artifact"
          echo "***Updating lambda Function $LAMBDA_FUNCTION_NAME*** with target/${ARTIFACT_NAME}***"
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://target/${ARTIFACT_NAME}
          sleep 10
          LAMBDA_VERSION=$(aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME | jq -r .Version)
          aws lambda update-alias --function-name $LAMBDA_FUNCTION_NAME --name $LAMBDA_ALIAS_NAME --function-version $LAMBDA_VERSION
          echo "LAMBDA UPDATE AND PUBLISH NEW VERSION DONE!!"
          
        elif [[ "${LAMBDA_UPDATE}" = "false" ]] ; then
          echo "Recieved LAMBDA_UPDATE as false, skipping lambda function update"
        else
          echo "Not a Lambda function, skipping the update"
        fi
  post_build:
    commands:
      - echo post_build started on `date`
      # add if condition to check if appspec.yml exists in the root directory
      - |
        if [[ "${LAMBDA_FUNCTION_NAME}" == "" ]]; then
          # code-deploy expects the appspec.yml file on the root directory, otherwise code-deploy will fail.
          pwd && ls -lrt

          # Find all instances of appspec.yml in the current and sub-directories
          found=$(find . -type f -name "appspec.yml")

          # Check if appspec.yml was not found
          if [ -z "$found" ]; then
              echo "Warning: appspec.yml not found. code-deploy expects the appspec.yml file on the root directory, otherwise code-deploy will fail."
          else
              # Iterate through the found files
              for file in $found; do
                  # Check if the file is in the $CODEBUILD_SRC_DIR directory
                  if [ "$(dirname "$file")" = "$CODEBUILD_SRC_DIR" ] ; then
                    echo "appspec.yml found in the $CODEBUILD_SRC_DIR directory, nothing to copy."
                  else
                    # Copy the file to the $CODEBUILD_SRC_DIR directory
                    cp "$file" "$CODEBUILD_SRC_DIR/"
                    echo "appspec.yml found in sub-directory and copied."
                  fi
              done
          fi
          echo "verifying appspec.yml" && ls -lrta $CODEBUILD_SRC_DIR
          echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
        fi

artifacts:
    files:
      - '**/*'

#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.m2/**/*'