# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - PROJECT_ROOT_DIRECTORY
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - DEPENDENCY_FILES_LOCATION
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH   : "${GIT_REPO_BRANCH}"
    GIT_REPO_URL      : "${GIT_REPO_URL}"
    LAMBDA_FUNCTION_NAME : "${LAMBDA_FUNCTION_NAME}"
    LAMBDA_ALIAS_NAME : "${LAMBDA_ALIAS_NAME}"
phases:
  install:
    runtime-versions:
      dotnet: $DOTNET_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - echo "codebuild app language - $CODEBUILDAPP_LANGUAGE"
      - echo "dotnet runtime - $DOTNET_RUNTIME"

      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure dotnet is installed"
      - echo "dotnet version is `dotnet --version`"
      - echo "Making sure GIT cli is installed"
      - echo `git --version`
      - echo "Making sure JFROG cli is installed"
      - echo `jf --version`
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase execution..."
      - echo Build started on `date`
      
      # verifying environment_variables
      - echo "PROJECT_ROOT_DIRECTORY - $PROJECT_ROOT_DIRECTORY"
      - echo "LAMBDA_FUNCTION_NAME - $LAMBDA_FUNCTION_NAME"
      - echo "EXCLUDE_FILES - $EXCLUDE_FILES"
      - echo "LAMBDA_UPDATE - $LAMBDA_UPDATE"
      - echo "DOTNET_PROJECT_METADATA_FILE - $DOTNET_PROJECT_METADATA_FILE"
      
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      
      - echo `pwd`
      - ls -lart
      
      - |
        if [ -f $DOTNET_PROJECT_METADATA_FILE ] ; then
           ARTIFACT_VERSION=$(cat $DOTNET_PROJECT_METADATA_FILE | jq -r .version)
           ARTIFACT_ID=$(cat $DOTNET_PROJECT_METADATA_FILE | jq -r .name)
           if [ "$ARTIFACT_VERSION" != "" ] && [ "$ARTIFACT_ID" != "" ] ; then
             ARTIFACT_FULL_NAME=$ARTIFACT_ID-$ARTIFACT_VERSION.zip
           else
             echo "$DOTNET_PROJECT_METADATA_FILE doesn't have the name and version attributes"
             exit 1;
           fi
        else
           echo "$DOTNET_PROJECT_METADATA_FILE is missing"
           exit 1;
        fi
      
      - echo "ARTIFACT_FULL_NAME - $ARTIFACT_FULL_NAME"
      
      # making zip file
      - echo "Zipping deployment package with Artifact name as $ARTIFACT_FULL_NAME."
      - zip -g $ARTIFACT_FULL_NAME * **/* -x appspec.* sonar-project.properties coverage.xml $EXCLUDE_FILES
      - zip -sf $ARTIFACT_FULL_NAME

      #generating path to deploy artifact into artifactory
      - ARTIFACTORY_REPO_KEY_PATH=$ARTIFACTORY_REPO_KEY/$ARTIFACT_ID/$ARTIFACT_VERSION/

      - echo " *** Printing Variables *** "
      - export SERVER_ID="$ARTIFACTORY_HOST"
      - export CODEBUILD_NAME=`echo "$CODEBUILD_BUILD_ID" | awk '{split($0,a,":"); print a[1]}'`

      - echo "CODEBUILD_BUILD_ID - $CODEBUILD_BUILD_ID"
      - echo "CODEBUILD_NAME - $CODEBUILD_NAME"
      - echo "CODEBUILD_BUILD_NUMBER - $CODEBUILD_BUILD_NUMBER"
      - echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - echo "GIT_REPO_URL - $GIT_REPO_URL"
      - echo "GIT_REPO_BRANCH - $GIT_REPO_BRANCH"
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION - $CODEBUILD_RESOLVED_SOURCE_VERSION"

      - echo "SERVER_ID - $SERVER_ID"
      - echo "ARTIFACTORY_REPO_KEY_PATH - $ARTIFACTORY_REPO_KEY_PATH"
      - echo "ARTIFACTORY_REPO_KEY - $ARTIFACTORY_REPO_KEY"
      - echo "ARTIFACT_FULL_NAME - $ARTIFACT_FULL_NAME"
      - echo "ARTIFACTORY_AUTH_PREFIX - $ARTIFACTORY_AUTH_PREFIX"

      # verifying jfrog connection
      - jf c add "$SERVER_ID" --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST" --interactive=false
      - jf c s
      - jf rt ping
      - pwd
      - ls -lrt
      
      - echo "Deploy Artifact $ARTIFACT_FULL_NAME to Artifactory Host $ARTIFACTORY_HOST with REPO-KEY-PATH $ARTIFACTORY_REPO_KEY_PATH"
            
       # Uploading Artifact
      - jf rt u "$ARTIFACT_FULL_NAME" $ARTIFACTORY_REPO_KEY_PATH --recursive=false --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST/artifactory" --build-name="$CODEBUILD_NAME" --build-number="$CODEBUILD_BUILD_NUMBER"
   
     # Collecting environment variables
      - jf rt bce "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER"

      - |
        if [ ! -f "version.toml" ] ; then
          echo "***version.toml does not exist, skipping setting properties, if you wish to download artifact from artifactory in QA or prod and skip build and scan stages, please provide version.toml file in root directory***"
          echo ""
        else
          echo "**** version.toml exists, getting values of group_id and artifact_id from version.toml ****"
          ARTIFACT_ID=$(cat version.toml | grep artifact_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_VERSION=$(cat version.toml | grep artifact_version | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACTORY_REPO_KEY=$(cat version.toml | grep artifact_group_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_FULL_NAME=$(cat version.toml | grep artifact_name | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_PATH=$ARTIFACT_ID/$ARTIFACT_VERSION
          echo "setting properties with branch name as ${GIT_REPO_BRANCH} on artifact"  
          jf rt sp "$ARTIFACTORY_REPO_KEY/$ARTIFACT_PATH/$ARTIFACT_FULL_NAME" "branch=${GIT_REPO_BRANCH}"
        fi  
           
      # Publishing dependencies
      - |
        if [ "$DEPENDENCY_FILES_LOCATION" != "" ] ; then
            jf rt bad "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" "$DEPENDENCY_FILES_LOCATION"
        fi
        
      # Publishing build-info
      - jf rt bp "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" --build-url="$CODEBUILD_BUILD_ARN"
      - jf rt bpr "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" $ARTIFACTORY_REPO_KEY --status="released"
     
      - jf c rm $SERVER_ID --quiet
      - jf c s
      
      # updating the Lambda function
      - | 
        if [[ "${LAMBDA_UPDATE}" = "true" && "${LAMBDA_FUNCTION_NAME}" != "" ]] ; then
          echo "***Updating lambda Function $LAMBDA_FUNCTION_NAME***"
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$ARTIFACT_FULL_NAME
          sleep 10
          LAMBDA_VERSION=$(aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME | jq -r .Version)
          aws lambda update-alias --function-name $LAMBDA_FUNCTION_NAME --name $LAMBDA_ALIAS_NAME --function-version $LAMBDA_VERSION
          echo "LAMBDA UPDATE AND PUBLISH NEW VERSION DONE with version $LAMBDA_VERSION!!"
        elif [[ "${LAMBDA_UPDATE}" = "false" && "$LAMBDA_FUNCTION_NAME" != "" ]] ; then
          echo "Recieved LAMBDA_UPDATE as false, skipping lambda function update"
        else
          echo "Not a Lambda function, skipping the update"
        fi
  post_build:
    commands:
      - echo post_build started on `date`
      # add if condition to check if appspec.yml exists in the root directory
      - |
        if [[ "${LAMBDA_FUNCTION_NAME}" == "" ]]; then
          # code-deploy expects the appspec.yml file on the root directory, otherwise code-deploy will fail.
          pwd && ls -lrt

          # Find all instances of appspec.yml in the current and sub-directories
          found=$(find . -type f -name "appspec.yml")

          # Check if appspec.yml was not found
          if [ -z "$found" ]; then
              echo "Warning: appspec.yml not found. code-deploy expects the appspec.yml file on the root directory, otherwise code-deploy will fail."
          else
              # Iterate through the found files
              for file in $found; do
                  # Check if the file is in the $CODEBUILD_SRC_DIR directory
                  if [ "$(dirname "$file")" = "$CODEBUILD_SRC_DIR" ] ; then
                    echo "appspec.yml found in the $CODEBUILD_SRC_DIR directory, nothing to copy."
                  else
                    # Copy the file to the $CODEBUILD_SRC_DIR directory
                    cp "$file" "$CODEBUILD_SRC_DIR/"
                    echo "appspec.yml found in sub-directory and copied."
                  fi
              done
          fi
          echo "verifying appspec.yml" && ls -lrta $CODEBUILD_SRC_DIR
          echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
        fi
        
artifacts:
    files:
      - '**/*'

#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.nuget/**/*'