project_name          = "webcore-pipelines"
environment           = "Dev"
app_id                = "2586"
data_classification   = "Internal"
cris                  = "Low"
notify                = ["aucm@pge.com"]
owner                 = ["A1P2", "C1MP", "C3T1"]
compliance            = ["None"]
order                 = "70039360"
aws_region            = "us-west-2"
suffix                = "devpipe01"
prefix                = "engagetest"
target_workspace      = "predev"
create_graph_pipeline = true
