output "id" {
  description = "The Configuration Profile ID generated by AWS"
  value       = aws_appconfig_configuration_profile.pge_profile.configuration_profile_id
}

output "arn" {
  description = "The ARN generated by AWS"
  value       = aws_appconfig_configuration_profile.pge_profile.arn
}

output "tags" {
  description = "A map of all tags associated with the resource."
  value       = aws_appconfig_configuration_profile.pge_profile.tags_all
}
