project_name         = "webcore-pipelines"
environment          = "Dev"
app_id               = "2586"
data_classification  = "Internal"
cris                 = "Low"
notify               = ["aucm@pge.com"]
owner                = ["A1P2", "C1MP", "C3T1"]
compliance           = ["None"]
aws_region           = "us-west-2"
suffix               = "dev"
prefix               = "engagetest"
target_workspace     = "predev"
create_seed_pipeline = true
order                = "70039360"
