# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - ARTIFACTORY_REPO_KEY_PATH
    - NODEJS_VERSION
    - PROJECT_NAME
  variables:
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    ARTIFACTORY_REPO_KEY : "${ARTIFACTORY_REPO_KEY}"
    ARTIFACTORY_REPO_KEY_PATH : "${ARTIFACTORY_REPO_KEY_PATH}"
phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:

      - echo listing files and directories
      - ls -lart

  pre_build:
    commands:
      - 'ls -lart'
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version


  build:
    commands:
      - echo Build started on `date`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo Compiling the Node.js code
      - 'ls -lart'
      - echo "Entered the install phase..."
      - echo Build started on `date`

      # Jfrog server conifguration
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - jf rt ping
      - jf c s

      # # Jfrog repo configuraiton
      - jf rt npmc --repo-deploy $ARTIFACTORY_REPO_KEY_PATH --repo-resolve $ARTIFACTORY_REPO_KEY

      # building project

      
      # building project
      - echo "codepipeline type - $CODEPIPELINE_TYPE"
      - echo Installing source NPM dependencies...
      - jf npm install
      - |
        if [ "$CODEPIPELINE_TYPE" == "angular" ] ; then
           jf npm install -g @angular/cli
           echo Building Angular Project
        fi
        
        if [[ -z $BUILD_ENV ]]; then 
             npm run build;
             echo "Building with default env build";
           else
             npm run build:$BUILD_ENV;
        fi
           
        if [ "$CODEPIPELINE_TYPE" == "angular" ] ; then
           ls -larth dist/$PROJECT_NAME/
        else
           ls -larth build/ 
        fi

artifacts:
  files:
      - ./**/*

#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.npm/**/*'