# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  exported-variables:
    - ARTIFACT_VERSION
    - PROJECT_NAME
    - PROJECT_ROOT_DIRECTORY
    - NODEJS_VERSION
    - ARTIFACTORY_HOST

  variables:
    SONAR_TOKEN                : "${SONAR_TOKEN}"
    SONAR_HOST                 : "${SONAR_HOST}"
    ARTIFACTORY_TOKEN          : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH            : "${GIT_REPO_BRANCH}"
    PROJECT_NAME               : "${PROJECT_NAME}"
    ARTIFACTORY_REPO_KEY       : "${ARTIFACTORY_REPO_KEY}"
    ARTIFACTORY_REPO_KEY_PATH  : "${ARTIFACTORY_REPO_KEY_PATH}"
    UNIT_TEST_COMMANDS         : "${UNIT_TEST_COMMANDS}"

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION_CODESCAN
    commands:
      - echo "Entered the installation phase..."
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version

      - echo "Installing Sonar Scanner CLI"
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -o sonar-scanner-cli-5.0.1.3006-linux.zip -d /var/tmp && rm -rf sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=/var/tmp/sonar-scanner-5.0.1.3006-linux/bin:$PATH
      - ls -lrt /var/tmp/
      - echo $PATH
      - echo "verifying sonar-scanner cli installation" && sonar-scanner -h

      # - echo Installing Mocha...
      # - jf npm install mocha
      - echo listing files and directories
      - ls -lart

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo Installing source NPM dependencies...

      # Jfrog server conifguration
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - jf rt ping
      - jf c s

      # # Jfrog repo configuraiton
      - jf rt npmc --repo-deploy $ARTIFACTORY_REPO_KEY_PATH --repo-resolve $ARTIFACTORY_REPO_KEY

      # - jf npm install -g sonarqube-scanner
      - sonar-scanner --version
      - echo "SONAR_HOST - $SONAR_HOST"
      - echo "PROJECT_NAME - $PROJECT_NAME"
      - echo "ARTIFACT_VERSION - $ARTIFACT_VERSION"
      - echo "PROJECT_ROOT_DIRECTORY - $PROJECT_ROOT_DIRECTORY"
      - echo present working directory `pwd`
  build:
    on-failure: ABORT
    commands:
      - echo sonar scan started on `date`
      - echo present working directory `pwd`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      # Running unit tests
      -  echo "$UNIT_TEST_COMMANDS"
      - |
        if [ -n "$UNIT_TEST_COMMANDS" ]; then
          echo "Running unit tests: $UNIT_TEST_COMMANDS"
          eval "$UNIT_TEST_COMMANDS"
        else
          echo "No unit test commands provided. Skipping unit tests."
        fi

      
      #running sonar analysis
      - echo "Running Sonar Analysis"
      # - export PATH=$CODEBUILD_SRC_DIR/sonar-scanner-5.0.1.3006-linux/bin:$PATH
      - sonar-scanner -D sonar.projectKey="$PROJECT_KEY" -D sonar.projectName="$PROJECT_NAME" -D sonar.branch.name="$GIT_REPO_BRANCH" -D sonar.token="$SONAR_TOKEN" -D sonar.host.url="$SONAR_HOST"

      # checking quality gate status
      - sleep 30;
      - curl -u "$SONAR_TOKEN:" -G --data-urlencode "branch=$GIT_REPO_BRANCH" --data-urlencode "projectKey=$PROJECT_KEY"  "$SONAR_HOST"/api/qualitygates/project_status > result.json
      - cat result.json
      # Quality scan validation. Build will fail for all enviroments other than Dev if ERROR/WARN found. Build will fail if QG is not attached.
      - |
        if [[ $(jq -r '.projectStatus.status' result.json) != OK ]] ; then
          echo "ERROR/WARN found or there's no QG attached in the Sonar server. Please verify"
          if [[ "${APP_ENVIRONMENT,,}" != "dev" ]] ; then
              export CODEBUILD_BUILD_SUCCEEDING=0 ;
          else
             echo "DEV environment, hence allowed with ERROR/WARN. Check and fix reported issues before moving to prod here - $SONAR_HOST/dashboard?id=$PROJECT_NAME" ;
          fi
        elif [[ $(jq -r '.projectStatus.status' result.json) == None ]] ; then 
          echo "Quality Gate status is None, verify if Quality Gate is attached to sonar project"
          export CODEBUILD_BUILD_SUCCEEDING=0 ;
        fi



  post_build:
    commands:  
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then 
            echo "Quality gate status is not success - exiting with error"
            echo " **** check your application vulnerabilities and coverage here - $SONAR_HOST/dashboard?id=$PROJECT_NAME"
            exit 1; 
        else
          echo 'Build Success'
        fi

artifacts:
    files:
      - '**/*'


#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.npm/**/*'