jobs:
- job: DeployInfraJob
  displayName: "Deploy Infrastructure"
  pool:
    vmImage: ubuntu-latest

  workspace:
    clean: all

  steps:

    ###########################################################################
    # Download App Artifact
    ###########################################################################
    - task: DownloadPipelineArtifact@2
      displayName: "Download infrastructure code"
      inputs:
        artifactName: epic-app
        targetPath: $(System.DefaultWorkingDirectory)/${{ parameters.appName }}


    ###########################################################################
    # Install Terraform
    ###########################################################################
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'


    ###########################################################################
    # Configure Git Credentials for Terraform
    ###########################################################################
    - bash: |
        git config --global url."https://$(GITHUB_PAT)@github.com/".insteadOf "https://github.com/"
      displayName: 'Configure Git credentials for Terraform'
      env:
        GITHUB_PAT: $(GITHUB_PAT)


    ###########################################################################
    # Cloud-specific Infrastructure
    ###########################################################################
    - template: ${{ parameters.cloudProvider }}.yml
      parameters:
        ${{ insert }}: ${{ parameters }}
