output "imagebuilder_recipe_arn" {
  description = "The ARN of the Imagebuilder image recipe"
  value       = module.ec2-image-builder.image_builder_image_recipe_arn
}

output "imagebuilder_infra_config_arn" {
  description = "The ARN of the Imagebuilder infrastructure configuration."
  value       = module.ec2-image-builder.infrastructure_configuration[0].arn
}

output "imagebuilder_image_arn" {
  description = "The ARN of the Imagebuilder image"
  value       = module.ec2-image-builder.image_builder_img[0].arn
}

output "imagebuilder_pipeline_arn" {
  description = "The ARN of the Imagebuilder pipeline."
  value       = module.ec2-image-builder.imagebuilder_image_pipeline[0].arn
}

output "instance_profile_name" {
  description = "The name of instance profile attached to the Imagebuilder."
  value       = module.ec2-image-builder.iam_instance_profile.name
}

output "imagebuilder_pipeline_id" {
  description = "The ID of the Imagebuilder pipeline."
  value       = module.ec2-image-builder.imagebuilder_image_pipeline[0].id
}

output "imagebuilder_image_name" {
  description = "The name of the Imagebuilder name."
  value       = module.ec2-image-builder.imagebuilder_image_pipeline[0].name
}

output "imagebuilder_creation_log" {
  description = "Logs of Imagebuilder Image Creation process."
  value       = module.ec2-image-builder.infrastructure_configuration[0].logging[0].s3_logs[0].s3_bucket_name
}

output "ami_id" {
  description = "AMI ID generated by the Imagebuilder Pipeline"
  value       = tolist(module.ec2-image-builder.image_builder_img[0].output_resources[0].amis)[0].image
}