# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACT_NAME
    - PROJECT_ROOT_DIRECTORY
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY    
    - PROJECT_FILE_LOCATION
    - DOTNET_VERSION
  variables:
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    S3_BINARIES_STORE : "${S3_BINARIES_STORE}"

phases:
  install:
    runtime-versions:
      dotnet: $DOTNET_VERSION
    commands:
      - Write-Host "Entered the install phase... (Windows)"

  pre_build:
    commands:
      - Write-Host ("Restore started on " + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
      - Write-Host "Making sure dotnet is installed"
      - Write-Host $DOTNET_VERSION
      - nuget restore Trade.sln
      - |
          # Download and install .NET Framework 4.8
          $installer = "$env:TEMP\ndp48-x86-x64-allos-enu.exe"
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2088631" -OutFile $installer
          Start-Process -FilePath $installer -ArgumentList "/q /norestart" -Wait
          Write-Host ".NET Framework 4.8 installation complete."
      - dotnet --version
      - dotnet --list-sdks
      - dotnet --list-runtimes

  build:
    commands:
      - Write-Host ("Build started on" + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
      - Write-Host "CODEBUILD_SRC_DIR - $env:CODEBUILD_SRC_DIR"
      - Get-ChildItem

      - |
          if ($env:PROJECT_ROOT_DIRECTORY -ne "") {
            Write-Host "Change directory to $env:PROJECT_ROOT_DIRECTORY"
            Set-Location $env:PROJECT_ROOT_DIRECTORY
            Get-ChildItem
          }
      - Get-ChildItem
      - Write-Host $env:PROJECT_FILE_LOCATION

      #- dotnet restore .
      - msbuild Trade.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.8

artifacts:
  files:
   - ./**/*
#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.nuget/**/*'
