###############################################################################
# EPIC — AWS IAM Role Module
#
# Tier: Tier 0 (Foundational)
#
# IMPORTANT:
#   • Most users should NOT interact with these variables directly.
#   • EPIC generates inputs automatically based on role intent.
#   • Advanced inputs exist for platform and security teams only.
###############################################################################

###############################################################################
# REQUIRED — Always provided (directly or via EPIC)
###############################################################################

variable "role_name" {
  description = "Name of the IAM role to create."
  type        = string
}

###############################################################################
# LEVEL 1 — SIMPLE INTENT-BASED USAGE (DEFAULT)
#
# These variables are primarily consumed by EPIC, not end users.
###############################################################################

variable "role_type" {
  description = <<EOT
High-level intent for the IAM role.

This value is interpreted by EPIC to automatically generate:
  • Trust relationships
  • Authentication mechanism
  • Default permissions
  • Security boundaries

Examples:
  - terraform
  - cicd
  - lambda
  - ecs
  - readonly
EOT

  type    = string
  default = null
}

###############################################################################
# LEVEL 2 — CAPABILITY-BASED EXTENSIONS (ADVANCED USERS)
###############################################################################

variable "capabilities" {
  description = <<EOT
Optional list of named capabilities that extend the role's permissions.

Capabilities are enterprise-defined abstractions that map to approved
policy sets (for example: s3_read, logs_write, secrets_read).

No IAM or Terraform knowledge is required to use capabilities.
EOT

  type    = list(string)
  default = []
}

###############################################################################
# LEVEL 3 — EXPERT / ESCAPE HATCH (SECURITY & PLATFORM ONLY)
#
# These variables expose raw IAM constructs and should be used sparingly.
###############################################################################

variable "custom_trust" {
  description = <<EOT
When true, disables EPIC-generated trust policies and enables explicit
trusted_principals configuration.

This should only be enabled for exceptional cases.
EOT

  type    = bool
  default = false
}

variable "trusted_principals" {
  description = <<EOT
Explicit trust relationships for the IAM role.

Used only when custom_trust is true.

Each entry represents a trusted entity allowed to assume the role.
EOT

  type = list(object({
    type      = string               # e.g. oidc, service, aws
    provider  = optional(string)     # e.g. ado, github, lambda.amazonaws.com
    subject   = optional(string)     # OIDC subject or condition
    account   = optional(string)     # AWS account ID or role ARN
  }))

  default = []
}

variable "policy_arns" {
  description = <<EOT
List of managed policy ARNs to attach to the role.

This input is typically generated by EPIC based on role_type and
capabilities. Direct usage is considered advanced.
EOT

  type    = list(string)
  default = []
}

variable "inline_policies" {
  description = <<EOT
Optional inline IAM policies to attach to the role.

This should only be used for rare, tightly-scoped scenarios.
EOT

  type    = map(string)
  default = {}
}

###############################################################################
# COMMON — TAGGING (ALWAYS APPLIED)
###############################################################################

variable "tags" {
  description = "Tags to apply to the IAM role."
  type        = map(string)
  default     = {}
}

