version: 0.2

phases:
  install:
    commands:
      - echo "Install SonarScanner"
      - wget -q -O sonar-scanner-cli.zip $SONAR_CLI_DOWNLOAD_URL
      - echo "Unzip"
      - unzip sonar-scanner-cli.zip
      - rm sonar-scanner-cli.zip
      - mv sonar-scanner-* /opt/sonar-scanner
      - echo -e "#/bin/bash\nexport PATH=$PATH:/opt/sonar-scanner/bin" >> /etc/profile.d/sonar-scanner.sh
      - source /etc/profile.d/sonar-scanner.sh
      - echo "Installing to opt..."
      - sonar-scanner -v
      - echo "Sonar Scanner is installed"
  build:
    commands:
      - bash ./buildspecs/buildspec-sonarqube.sh
  post_build:
    commands:
      - echo SonarQube Scanner completed on `date`
