#api_gateway_api_key
variable "api_key_name" {
  description = "The name of the API key."
  type        = string
}

variable "api_key_description" {
  description = "The API key description. Defaults to \"Managed by Terraform\"."
  type        = string
  default     = null
}

variable "api_key_enabled" {
  description = "Specifies whether the API key can be used by callers. Defaults to true."
  type        = bool
  default     = true
}

variable "api_key_value" {
  description = "The value of the API key. If not specified, it will be automatically generated by AWS on creation."
  type        = string
  default     = null
}

#Variables for api_key
variable "tags" {
  description = "Key-value map of resource tags"
  type        = map(string)
}

module "validate_tags" {
  source  = "app.terraform.io/pgetech/validate-pge-tags/aws"
  version = "0.1.2"
  tags    = var.tags
}