# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.

version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - PROJECT_NAME
    - SONAR_HOST
    - PROJECT_ROOT_DIRECTORY
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    SONAR_TOKEN            : "${SONAR_TOKEN}"
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH   : "${GIT_REPO_BRANCH}"
    UNIT_TEST_COMMANDS : "${UNIT_TEST_COMMANDS}"
phases:
  install:
    runtime-versions:
      python: $PYTHON_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - echo "Installing sqlite3"
      - whereis sqlite3 && sqlite3 -version
      - wget https://www.sqlite.org/2020/sqlite-autoconf-3320300.tar.gz
      - tar xf sqlite-autoconf-3320300.tar.gz
      - (cd sqlite-autoconf-3320300; ./configure --prefix=/usr/local/ && make && make install)
      - export LD_LIBRARY_PATH="/usr/local/lib/"
      - python -c "import sqlite3; print(sqlite3.sqlite_version)"

      - echo "Installing Sonar Scanner CLI"
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip && rm -rf sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=sonar-scanner-5.0.1.3006-linux/bin:$PATH
      - echo "verifying sonar-scanner cli installation" && sonar-scanner -h

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure python is installed"
      - echo "python version is `python --version`" && echo "pip version is `pip --version`"
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the Build phase..."
      - echo Build started on `date`
      - echo `pwd`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo `pwd`
      - ls -lart
      # verifying environment_variables
      - echo "PROJECT_NAME - $PROJECT_NAME"
      
      #running sonar analysis
      - echo "Running Sonar Analysis"
      - export PATH=$CODEBUILD_SRC_DIR/sonar-scanner-5.0.1.3006-linux/bin:$PATH
      - sonar-scanner -D sonar.projectKey="$PROJECT_KEY" -D sonar.projectName="$PROJECT_NAME" -D sonar.branch.name="$GIT_REPO_BRANCH" -D sonar.login="$SONAR_TOKEN" -D sonar.host.url="$SONAR_HOST"
      # checking quality gate status
      - sleep 30
      - echo "checking SonarQube Quality Gate Status"
      - curl -s -u "$SONAR_TOKEN:" -G --data-urlencode "branch=$GIT_REPO_BRANCH" --data-urlencode "projectKey=$PROJECT_KEY"  "$SONAR_HOST"/api/qualitygates/project_status > result.json
      - cat result.json
      - |
        if [ $(jq -r '.projectStatus.status' result.json) != OK ] ; then
           echo "Quality gate status is not success - exiting with error"
           echo " **** check your application vulnerabilities and coverage here - $SONAR_HOST"
           exit 1;
        fi
artifacts:
    files:
      - '**/*'
