# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  exported-variables:
    - ARTIFACT_VERSION
    - PROJECT_NAME
    - PROJECT_ROOT_DIRECTORY
    - NODEJS_VERSION

  variables:
    SONAR_TOKEN            : "${SONAR_TOKEN}"
    SONAR_HOST             : "${SONAR_HOST}"
    ARTIFACTORY_TOKEN      : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH        : "${GIT_REPO_BRANCH}"
    PROJECT_NAME           : "${PROJECT_NAME}"

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - echo "Entered the installation phase..."
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - echo Installing Mocha...
      - npm install mocha
      - echo listing files and directories
      - ls -lart

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo Installing source NPM dependencies...

      - npm install -g sonarqube-scanner
      - sonar-scanner --version
      - echo "SONAR_HOST - $SONAR_HOST"
      - echo "PROJECT_NAME - $PROJECT_NAME"
      - echo "ARTIFACT_VERSION - $ARTIFACT_VERSION"
      - echo "PROJECT_ROOT_DIRECTORY - $PROJECT_ROOT_DIRECTORY"
      - echo present working directory `pwd`
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo present working directory `pwd`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      # Running unit tests.
      # - echo "Running unit test"
      # - npm run test
 

      # Running Sonar Code Analysis
      - echo "Running Sonar Analysis"
      - sonar-scanner -Dsonar.projectKey="${PROJECT_KEY}" -Dsonar.projectName="${PROJECT_NAME}" -Dsonar.sources=. -Dsonar.host.url="${SONAR_HOST}" -Dsonar.token="${SONAR_TOKEN}" -Dsonar.branch.name=$GIT_REPO_BRANCH

      # checking quality gate status
      - sleep 30;
      - curl -u "$SONAR_TOKEN:" -G --data-urlencode "branch=$GIT_REPO_BRANCH" --data-urlencode "projectKey=$PROJECT_KEY"  "$SONAR_HOST"/api/qualitygates/project_status > result.json
      - cat result.json
      # Quality scan validation. Build will fail for all enviroments other than Dev if ERROR/WARN found. Build will fail if QG is not attached.
      - |
        if [[ $(jq -r '.projectStatus.status' result.json) != OK ]] ; then
          echo "ERROR/WARN found or there's no QG attached in the Sonar server. Please verify"
          if [[ "${APP_ENVIRONMENT,,}" != "dev" ]] ; then
              export CODEBUILD_BUILD_SUCCEEDING=0 ;
          else
             echo "DEV environment, hence allowed with ERROR/WARN. Check and fix reported issues before moving to prod here - $SONAR_HOST/dashboard?id=$PROJECT_NAME" ;
          fi
        elif [[ $(jq -r '.projectStatus.status' result.json) == None ]] ; then 
          echo "Quality Gate status is None, verify if Quality Gate is attached to sonar project"
          export CODEBUILD_BUILD_SUCCEEDING=0 ;
        fi



  post_build:
    commands:  
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then 
            echo "Quality gate status is not success - exiting with error"
            echo " **** check your application vulnerabilities and coverage here - $SONAR_HOST/dashboard?id=$PROJECT_NAME"
            exit 1; 
        else
          echo 'Build Success'
        fi

artifacts:
    files:
      - '**/*'


#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.npm/**/*'