output "id" {
  description = "The Configuration Profile ID generated by AWS"
  value       = aws_appconfig_hosted_configuration_version.pge_hosted_config.configuration_profile_id
}

output "arn" {
  description = "The ARN generated by AWS"
  value       = aws_appconfig_hosted_configuration_version.pge_hosted_config.arn
}

output "version" {
  description = "Version number of the hosted configuration."
  value       = aws_appconfig_hosted_configuration_version.pge_hosted_config.version_number
}
