# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACT_NAME
    - PROJECT_ROOT_DIRECTORY
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - ARTIFACTORY_REPO_KEY_PATH
    - ARTIFACTORY_UPLOAD_FILE
    - NODEJS_VERSION
  variables:
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    ARTIFACTORY_REPO_KEY : "${ARTIFACTORY_REPO_KEY}"
    ARTIFACTORY_REPO_KEY_PATH : "${ARTIFACTORY_REPO_KEY_PATH}"
    ARTIFACTORY_UPLOAD_FILE : "${ARTIFACTORY_UPLOAD_FILE}"
phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:

      - echo listing files and directories
      - ls -lart

  pre_build:
    commands:
      - ls -lart
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version



  build:
    commands:
      - echo Build started on `date`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo Compiling the Node.js code
      - 'ls -lart'
      - echo "Entered the install phase..."
      - echo Build started on `date`

      # Jfrog server conifguration
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - jf rt ping
      - jf c s

      # # Jfrog repo configuraiton
      - jf rt npmc --repo-deploy $ARTIFACTORY_REPO_KEY_PATH --repo-resolve $ARTIFACTORY_REPO_KEY

      # building project
      - echo Installing source NPM dependencies...
      - jf npm install
      - jf npm install -g @angular/cli
      - echo Building Angular Project
      - npm run build
      - ls -larth node_modules/
      # # - echo present working directory `pwd`
      # - zip -r $ARTIFACTORY_UPLOAD_FILE.zip .

      # # If we have a secondary input source we need to change directory to that input source before we perform any commands specific to that input artifact
      # - echo `pwd`
      # - ls -lart

# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  #base-directory: $PROJECT_ROOT_DIRECTORY
  #name: $PROJECT_ROOT_DIRECTORY-$CODEBUILD_BUILD_NUMBER.zip
  files:
      - ./**/*