# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACT_VERSION
    - PROJECT_NAME
    - PROJECT_ROOT_DIRECTORY
    - PROJECT_UNIT_TEST_DIRECTORY
    - DOTNET_VERSION
  variables:
    SONAR_TOKEN            : "${SONAR_TOKEN}"
    ARTIFACTORY_TOKEN      : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH        : "${GIT_REPO_BRANCH}"
    UNIT_TEST_COMMANDS     : "${UNIT_TEST_COMMANDS}"
phases:
  install:
    runtime-versions:
      dotnet: $DOTNET_VERSION
    commands:
      - echo "Entered the install phase..."
      
      # Install dotnet-sonarscanner          
      - dotnet tool install --global dotnet-sonarscanner
      
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      
      - echo "Making sure dotnet is installed"
      - echo `dotnet --version`
      - dotnet --list-sdks
      - dotnet --list-runtimes
      
                       
      - echo "SONAR_HOST - $SONAR_HOST"
      - echo "PROJECT_NAME - $PROJECT_NAME"
      - echo "ARTIFACT_VERSION - $ARTIFACT_VERSION"
      - echo "PROJECT_ROOT_DIRECTORY - $PROJECT_ROOT_DIRECTORY"
      - echo "PROJECT_UNIT_TEST_DIRECTORY - $PROJECT_UNIT_TEST_DIRECTORY"
      - echo "GIT_REPO_BRANCH - $GIT_REPO_BRANCH"

  build:
    on-failure: ABORT
    commands:
      - echo "Entered the install phase..."
      - echo Build started on `date`

      
      # - cd $CODEBUILD_SRC_DIR_BuildOutMuti-Step-Build-APP
      # If we have a secondary input source we need to change directory to that input source before we perform any commands specific to that input artifact
      - echo `pwd`
      - ls -lart
    
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo `pwd`
      - ls -lart
      
      # running unit test
      - echo "Running unit test"      
      - |
        if [ -z "$PROJECT_UNIT_TEST_DIRECTORY" ]; then 
          echo "Error: PROJECT_UNIT_TEST_DIRECTORY is not set"
        else
          echo "running unit tests with following command $UNIT_TEST_COMMANDS"
          eval $UNIT_TEST_COMMANDS
          ls -lrta
          ls -lrt ./testresults
        fi

      #running sonar analysis
      - echo "Running Sonar Analysis"
       
      - dotnet sonarscanner begin /k:$PROJECT_NAME /d:sonar.host.url="$SONAR_HOST" /d:sonar.token="$SONAR_TOKEN" /v:"$ARTIFACT_VERSION" /d:sonar.branch.name="$GIT_REPO_BRANCH"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

      # checking quality gate status
      - sleep 30;
      - echo "checking SonarQube Quality Gate Status"
      - curl -s -u "$SONAR_TOKEN:" -G --data-urlencode "branch=$GIT_REPO_BRANCH" --data-urlencode "projectKey=$PROJECT_KEY"  "$SONAR_HOST"/api/qualitygates/project_status > result.json
      - cat result.json    
      - |
        if [[ $(jq -r '.projectStatus.status' result.json) != OK ]] ; then
            echo "ERROR/WARN found or there's no QG attached in the Sonar server. Please verify"
            if [[ "${APP_ENVIRONMENT,,}" != "dev" ]] ; then
                export CODEBUILD_BUILD_SUCCEEDING=0 ;
            else
                echo "DEV environment, hence allowed with ERROR/WARN. Check and fix reported issues before moving to prod here - $SONAR_HOST/dashboard?id=$PROJECT_NAME" ;
            fi
        elif [[ $(jq -r '.projectStatus.status' result.json) == None ]] ; then
            echo "Quality Gate status is None, verify if Quality Gate is attached to sonar project"
            export CODEBUILD_BUILD_SUCCEEDING=0 ;
        fi
        
artifacts:
  files:
    - ./**/*
#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.nuget/**/*'