#Variables for tags
variable "tags" {
  description = "A map of tags to assign to the resource"
  type        = map(string)
}

module "validate_tags" {
  source  = "app.terraform.io/pgetech/validate-pge-tags/aws"
  tags    = var.tags
  version = "0.1.2"
}

#Variables for event subscription
variable "enabled" {
  description = "A boolean flag to enable/disable the subscription. Defaults to true."
  type        = bool
  default     = true
}

variable "event_categories" {
  description = "A list of event categories for a source_type that you want to subscribe to. If the end user is not passing any values to this variable, then it will take all the possible values."
  type        = list(string)
  default     = []
  validation {
    condition = alltrue([
      for i in var.event_categories : contains(["availability", "backtrack", "backup", "configuration change", "creation", "deletion", "failover", "failure", "low storage", "maintenance", "notification", "read replica", "recover", "restoration", "global-failover"], i)
    ])
    error_message = "Error! values for event_categories are availability, backtrack, backup, configuration change, creation, deletion, failover, failure, low storage, maintenance, notification, read replica, recover, restoration, global-failover."
  }
}

variable "name" {
  description = "The name of the Neptune event subscription. By default generated by Terraform."
  type        = string
}

variable "sns_topic_arn" {
  description = "The ARN of the SNS topic to send events to."
  type        = string
  validation {
    condition = anytrue([
      can(regex("^arn:aws:sns:\\w+(?:-\\w+)+:[[:digit:]]{12}:([a-zA-Z0-9])+(.*)$", var.sns_topic_arn))
    ])
    error_message = "The sns_topic_arn is required and the allowed format of 'sns_topic_arn' is arn:aws:sns:<region>:<account-id>:<sns-topic-name>."
  }
}

variable "neptune_source" {
  description = <<-DOC
    source_ids:
       A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a source_type must also be specified.
    source_type:
      The type of source that will be generating the events. Valid options are db-instance, db-security-group, db-parameter-group, db-snapshot, db-cluster or db-cluster-snapshot. If not set, all sources will be subscribed to.
  DOC
  type = object({
    source_ids  = list(string)
    source_type = string
  })
  default = {
    source_ids  = null
    source_type = null
  }
  validation {
    condition = anytrue([
      var.neptune_source.source_type == null,
      var.neptune_source.source_type == "db-instance",
      var.neptune_source.source_type == "db-security-group",
      var.neptune_source.source_type == "db-parameter-group",
      var.neptune_source.source_type == "db-snapshot",
      var.neptune_source.source_type == "db-cluster",
    var.neptune_source.source_type == "db-cluster-snapshot"])
    error_message = "Error! values for source_type should be db-instance, db-security-group, db-parameter-group, db-snapshot, db-cluster and db-cluster-snapshot."
  }
}

variable "event_subscription_timeouts" {
  description = "The event subscription timeouts should be in the format 40m for 40 minutes, 10s for ten seconds, or 2h for two hours."
  type        = list(map(string))
  default = [{
    create = "40m"
    delete = "40m"
    update = "40m"
  }]
}