version: 0.2

env:
  shell: bash
  parameter-store:
    GITHUB_TOKEN: MRAD_GITHUB_TOKEN
  secrets-manager:
    WIZ_CLIENT_ID: "shared-wiz-access:WIZ_CLIENT_ID"
    WIZ_CLIENT_SECRET: "shared-wiz-access:WIZ_CLIENT_SECRET"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing WIZ CLI"
      - mkdir -p /tmp/wizcli
      - curl -o /tmp/wizcli/wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
      - chmod +x /tmp/wizcli/wizcli
      - /tmp/wizcli/wizcli version
      - /tmp/wizcli/wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
  build:
    commands:
      - pwd
      - env | sort
      - ls -al
      # Exists in the Engage-Graph repository
      - ./buildspecs/buildspec-tfc-consumer.sh
