# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - PROJECT_ROOT_DIRECTORY
    - BUILD_FILE_PATH_LOCATION
    - DOTNET_RUNTIME
phases:
  install:
   runtime-versions:
     dotnet: $DOTNET_RUNTIME
   commands:
     - echo "Entered the install phase..."
     
      #Download the latest stable `nuget.exe` to `/usr/local/bin`
     - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe     
     - mv nuget.exe /usr/local/bin

  pre_build:
    commands:
      - echo "Entered the pre-build phase..."
      
      - echo "Making sure dotnet is installed"
      - echo `dotnet --version`
      - dotnet --list-sdks
      - dotnet --list-runtimes
      
      # Setting up Jfrog as the source artifactory
      - mono /usr/local/bin/nuget.exe sources Add -Name Artifactory -Source $ARTIFACTORY_HOST/artifactory/api/nuget/$ARTIFACTORY_REPO_KEY -username $ARTIFACTORY_USER -password $ARTIFACTORY_TOKEN
      - mono /usr/local/bin/nuget.exe setapikey $ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -Source Artifactory
            
  build:
    commands:
      - echo Build started on `date`
      
      # verifying environment_variables
      - echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - echo "PROJECT_ROOT_DIRECTORY - $PROJECT_ROOT_DIRECTORY"
      - echo "BUILD_FILE_PATH_LOCATION - $BUILD_FILE_PATH_LOCATION"
      
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - pwd
      - ls -lrta
      
      #Downloads and installs a package into a project, defaulting to the current folder, using jfrog artifactory as package sources
      - |
        if [ -f $BUILD_FILE_PATH_LOCATION/packages.config ] ; then 
          mono /usr/local/bin/nuget.exe install $BUILD_FILE_PATH_LOCATION/packages.config -Source Artifactory
        elif [ -f $BUILD_FILE_PATH_LOCATION/*.sln ] ; then
          mono /usr/local/bin/nuget.exe restore $BUILD_FILE_PATH_LOCATION/*.sln -Source Artifactory
        elif [ -f $BUILD_FILE_PATH_LOCATION/*.csproj ] ; then
          dotnet restore $BUILD_FILE_PATH_LOCATION
        fi
      
      #Publishing the application and its dependencies to a folder
      - dotnet publish -c release -r linux-x64 -o ./build_artifacts $BUILD_FILE_PATH_LOCATION

      - ls -lrta ./build_artifacts
      - ls -lart

artifacts:
  files:
   - ./**/*
#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.nuget/**/*'