# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables: #export environment variables from the current build stage to subsequent stages in the pipeline
    - PROJECT_ROOT_DIRECTORY
    - NODEJS_VERSION
phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - echo "Entered the install phase..."
      - echo "validating node version"
      - node --version & npm --version
  pre_build:
    commands:
      - echo "Entered the pre build phase..."
      - echo "Install JFROG CLI"
      - echo "[jfrog-cli]" > jfrog-cli.repo
      - echo "name=jfrog-cli" >> jfrog-cli.repo
      - echo "baseurl=https://releases.jfrog.io/artifactory/jfrog-rpms" >> jfrog-cli.repo
      - echo "enabled=1" >> jfrog-cli.repo
      - yum install -y wget
      - wget https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key
      - sed -i -e '$a\' jfrog_public_gpg.key
      - rpm --import jfrog_public_gpg.key
      - mv jfrog-cli.repo /etc/yum.repos.d/
      - yum install -y jfrog-cli-v2-jf

  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase execution..."
      - echo Build started on `date`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo present working directory `pwd`
      # Jfrog server conifguration
      - jf c add "${ARTIFACTORY_HOST}" --access-token="${ARTIFACTORY_TOKEN}" --url="${ARTIFACTORY_HOST}" --interactive=false
      - jf rt ping
      - jf c s

      # # Jfrog repo configuraiton
      - jf npmc --repo-deploy $ARTIFACTORY_REPO_KEY --repo-resolve $ARTIFACTORY_REPO_KEY

      # Installing required dependeincies and building project
      - echo Installing source NPM dependencies...
      - jf npm install
      - ls -l node_modules/
  post_build:
    commands:
      - echo "Entered the post_build phase execution..."


# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
    files:
      - '**/*'
#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.npm/**/*'