# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.

version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - PROJECT_NAME
    - SONAR_HOST
    - PROJECT_ROOT_DIRECTORY
  variables:
    SONAR_TOKEN         : "${SONAR_TOKEN}"
    ARTIFACTORY_TOKEN   : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH     : "${GIT_REPO_BRANCH}"
    UNIT_TEST_COMMANDS  : "${UNIT_TEST_COMMANDS}"    
phases:
  install:
    runtime-versions:
      dotnet: $DOTNET_RUNTIME
    commands:
      - echo "Entered the install phase..."
      
      # Install dotnet-sonarscanner          
      - dotnet tool install --global dotnet-sonarscanner

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure dotnet is installed"
      - echo "dotnet version is `dotnet --version`"
      - dotnet --list-sdks
      - dotnet --list-runtimes
      
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the Build phase..."
      - echo Build started on `date`
      
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - echo `pwd`
      - ls -lart
      
      # verifying environment_variables
      - echo "PROJECT_NAME - $PROJECT_NAME"
      - echo "PROJECT_ROOT_DIRECTORY - $PROJECT_ROOT_DIRECTORY"
      - echo "SONAR_HOST - $SONAR_HOST"

      #running Unit tests
      - echo "running unit tests with following command $UNIT_TEST_COMMANDS"
      - eval $UNIT_TEST_COMMANDS
      - ls -lrta
      
      #running sonar analysis
      - echo "Running Sonar Analysis"
       
      - dotnet sonarscanner begin /k:$PROJECT_NAME /k:$PROJECT_KEY /d:sonar.host.url="$SONAR_HOST" /d:sonar.token="$SONAR_TOKEN" /d:sonar.branch.name="$GIT_REPO_BRANCH"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

      
      # checking quality gate status
      - sleep 30
      - echo "checking SonarQube Quality Gate Status"
      - curl -s -u "$SONAR_TOKEN:" -G --data-urlencode "branch=$GIT_REPO_BRANCH" --data-urlencode "projectKey=$PROJECT_KEY"  "$SONAR_HOST"/api/qualitygates/project_status > result.json
      - cat result.json
      
      # Quality scan validation. Build will fail for all enviroments other than Dev if ERROR/WARN found. Build will fail if QG is not attached.
      - |
        if [[ $(jq -r '.projectStatus.status' result.json) != OK ]] ; then
          if [[ "${APP_ENVIRONMENT,,}" != "dev" ]] ; then
              export CODEBUILD_BUILD_SUCCEEDING=0 ;
          else
             echo "DEV environment, hence allowed with ERROR/WARN. Check and fix reported issues before moving to prod here - $SONAR_HOST/dashboard?id=$PROJECT_NAME" ;
          fi
        elif [[ $(jq -r '.projectStatus.status' result.json) == None ]] ; then 
          echo "Quality Gate status is None, verify if Quality Gate is attached to sonar project"
          export CODEBUILD_BUILD_SUCCEEDING=0 ;
        fi

  post_build:
    commands:  
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then 
            echo "Quality gate status is not success - exiting with error"
            echo " **** check your application vulnerabilities and coverage here - $SONAR_HOST/dashboard?id=$PROJECT_NAME"
            exit 1; 
        else
          echo 'Build Success'
        fi
        
       
artifacts:
    files:
      - '**/*'


#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
    - '/root/.nuget/**/*'