# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - ARTIFACTORY_HOST
    - ARTIFACTORY_REPO_KEY
    - DEPENDENCY_FILES_LOCATION
  variables:
    ARTIFACTORY_AUTH_PREFIX: 'Authorization:'
    ARTIFACTORY_TOKEN : "${ARTIFACTORY_TOKEN}"
    GIT_REPO_BRANCH   : "${GIT_REPO_BRANCH}"
    GIT_REPO_URL      : "${GIT_REPO_URL}"
phases:
  install:
    runtime-versions:
      java: $JAVA_RUNTIME
    commands:
      - echo "Entered the install phase..."
      - yum install -y git
      - echo "Install JFROG CLI"
      - curl -k -fL https://install-cli.jfrog.io | sh && jf --version

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Making sure Java is installed"
      - echo `java -version`
      - echo "Making sure Maven is installed"
      - echo `mvn --version`
      - echo "CCOE-3824 - Making sure GIT cli is installed"
      - echo `git --version`
      - echo "Making sure JFROG cli is installed"
      - echo `jf --version`
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase execution..."
      - echo Build started on `date`
      - |
        if [ "$PROJECT_ROOT_DIRECTORY" != "" ] ; then
          echo "Change directory to $PROJECT_ROOT_DIRECTORY"
          cd $PROJECT_ROOT_DIRECTORY
          ls -l
        fi
      - ls -lrt target/
      - echo "Deploy maven package to Artifactory Host"
      - export COMMAND=$(echo "mvn deploy -DskipTests -Dinternal_user=$ARTIFACTORY_USER -Dinternal_pw=$ARTIFACTORY_TOKEN ${OPTIONAL_ATTRIBUTES} -s settings.xml")
      - echo $COMMAND
      - eval $COMMAND

      - export SERVER_ID="$ARTIFACTORY_HOST"
      - export CODEBUILD_NAME=`echo "$CODEBUILD_BUILD_ID" | awk '{split($0,a,":"); print a[1]}'`

      - echo "CODEBUILD_BUILD_ID - $CODEBUILD_BUILD_ID"
      - echo "CODEBUILD_NAME - $CODEBUILD_NAME"
      - echo "CODEBUILD_BUILD_NUMBER - $CODEBUILD_BUILD_NUMBER"
      - echo "CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - echo "GIT_REPO_URL - $GIT_REPO_URL"
      - echo "GIT_REPO_BRANCH - $GIT_REPO_BRANCH"
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION - $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "SERVER_ID - $SERVER_ID"

      - echo "ARTIFACTORY_REPO_KEY - $ARTIFACTORY_REPO_KEY"
      - echo "ARTIFACTORY_AUTH_PREFIX - $ARTIFACTORY_AUTH_PREFIX"
      - echo "ARTIFACTORY_USER - $ARTIFACTORY_USER"

      - jf c add "$SERVER_ID" --access-token="$ARTIFACTORY_TOKEN" --url="$ARTIFACTORY_HOST" --interactive=false
      - jf c s
      - jf rt ping

      - jf rt bce "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER"

      - |
        if [ ! -f "version.toml" ] ; then
          echo "***version.toml does not exist, skipping setting properties, if you wish to download artifact from artifactory in QA or pro and skip build and scan stages, please provide version.toml file in root directory***"
        else
          echo "**** version.toml exists, getting values of group_id and artifact_id from version.toml ****"
          ARTIFACT_GROUPID=$(cat version.toml | grep group_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          VERSION=$(cat version.toml | grep version | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_ID=$(cat version.toml | grep artifact_id | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_NAME=$(cat version.toml | grep artifact_name | cut -d'=' -f2 | tr -d ' ' | tr -d '"')
          ARTIFACT_PATH=$ARTIFACT_GROUPID/$ARTIFACT_ID/$VERSION
   
          echo "setting properties with branch name as ${GIT_REPO_BRANCH} on artifact"  
          jf rt sp "$ARTIFACTORY_REPO_KEY/$ARTIFACT_PATH/$ARTIFACT_NAME" "branch=${GIT_REPO_BRANCH}"
        fi

      # Publishing dependencies
      - |
        if [ "$DEPENDENCY_FILES_LOCATION" != "" ] ; then
            jf rt bad "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" "$DEPENDENCY_FILES_LOCATION"
        fi
      # Publishing build-info
      - jf rt bp "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" --build-url="$CODEBUILD_BUILD_ARN"
      - jf rt bpr "$CODEBUILD_NAME" "$CODEBUILD_BUILD_NUMBER" $ARTIFACTORY_REPO_KEY --status="released"
      - jf c rm $SERVER_ID --quiet
      - jf c s
  post_build:
    commands:
      - echo "only required if appspec.yml exists other than root directory"
      - find . -type f -name "appspec.yml" -exec cp {} $CODEBUILD_SRC_DIR/ \;
      - echo "verifying appspec.yml" && ls $CODEBUILD_SRC_DIR/appspec.yml
      - ls -la

artifacts:
    files:
      - '**/*'

#adding default cache paths, https://docs.aws.amazon.com/codeartifact/latest/ug/dependency-caching.html
cache:
  paths:
  - '/root/.m2/**/*'