// <auto-generated />
using System;
using Epic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epic.Api.Data.Migrations
{
    [DbContext(typeof(EpicDbContext))]
    [Migration("20260323162140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epic.Api.Data.Entities.AppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwsAccountId")
                        .HasColumnType("text");

                    b.Property<string>("AwsCloudfront")
                        .HasColumnType("text");

                    b.Property<string>("AwsEc2InstanceId")
                        .HasColumnType("text");

                    b.Property<string>("AwsS3")
                        .HasColumnType("text");

                    b.Property<string>("AzureResourceGroup")
                        .HasColumnType("text");

                    b.Property<string>("AzureSubscription")
                        .HasColumnType("text");

                    b.Property<string>("Cloud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DotnetVersion")
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubRepo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JavaVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeVersion")
                        .HasColumnType("text");

                    b.Property<string>("PythonVersion")
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GithubRepo")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("Epic.Api.Data.Entities.PipelineRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageAppDeploy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageBuild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageInfraDeploy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageScan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageTest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("Epic.Api.Data.Entities.UserAppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId", "AppId")
                        .IsUnique();

                    b.ToTable("user_apps", (string)null);
                });

            modelBuilder.Entity("Epic.Api.Data.Entities.PipelineRunEntity", b =>
                {
                    b.HasOne("Epic.Api.Data.Entities.AppEntity", "App")
                        .WithMany("Runs")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Epic.Api.Data.Entities.UserAppEntity", b =>
                {
                    b.HasOne("Epic.Api.Data.Entities.AppEntity", "App")
                        .WithMany("UserApps")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Epic.Api.Data.Entities.AppEntity", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("UserApps");
                });
#pragma warning restore 612, 618
        }
    }
}
